### ISSUE TITLE
Feature request: select/mark multiple candidates

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#152]
Is it possible to select (i.e mark) multiple candidates in the denite prompt? I've read the docs but haven't found any reference (and it's a feature I really used in Unite).
Thanks!!

**Comment by fiz1ct** [comment]
Hit <Space> in normal mode. If you're in insert mode (by default you are most likely) then hit <C-O> to get into normal mode.

**Comment by rafi** [comment]
`:h denite-map-toggle_select`

**Comment by petobens** [comment]
@rafi @fiz1ct thanks! However using:
```
call denite#custom#map('insert', '<C-Space>', '<denite:toggle_select_up>',
            \ 'noremap')
```
 gives the following error:
```

Error detected while processing function denite#helper#call_denite[14]..denite#start[23].._denite_start:
line    1:
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self.__uis[buffer_name].start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 102, in start
[denite]     self.change_mode(self.__current_mode)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 369, in change_mode
[denite]     custom.get(mode, [])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keymap.py", line 163, in register_from_rules
[denite]     self.register_from_rule(nvim, rule)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keymap.py", line 134, in register_from_rule
[denite]     self.register(Definition.parse(nvim, rule))
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keymap.py", line 53, in parse
[denite]     lhs = Keystroke.parse(nvim, lhs)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keystroke.py", line 53, in parse
[denite]     keys = _ensure_keys(nvim, expr)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keystroke.py", line 63, in _ensure_keys
[denite]     for k in KEYS_PATTERN.findall(expr_bytes)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keystroke.py", line 63, in <genexpr>
[denite]     for k in KEYS_PATTERN.findall(expr_bytes)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/key.py", line 160, in parse
[denite]     code = _resolve(nvim, expr)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/key.py", line 189, in _resolve
[denite]     code = _resolve_from_special_keys(nvim, inner)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/key.py", line 206, in _resolve_from_special_keys
[denite]     _resolve_from_special_keys(nvim, inner[2:]),
[denite] TypeError: sequence item 1: expected a bytes-like object, int found
[denite] Please execute :messages command.
```

**Comment by petobens** [comment]
It has something to do with `C-Space` since:
```
call denite#custom#map('insert', '<C-m>', '<denite:toggle_select_up>',
            \ 'noremap')
```
works just fine.

**Comment by Shougo** [comment]
I will test `<C-Space>` mapping behavior.

**Comment by lambdalisue** [comment]
Confirmed and a new issue was created on neovim-prompt https://github.com/lambdalisue/neovim-prompt/issues/6

**Comment by lambdalisue** [comment]
#153 should fix the issue on `<C-Space>` but

1. Vim use `<C-@>` for `<C-@>`, `<C-Space>`, and `<C-S-Space>`
2. Neovim use `<C-Space>` for `<C-@>`, `<C-Space>`, and `<C-S-Space>`
3. GVim correctly use `<C-@>`, `<C-Space>`, and `<C-S-Space>`

So if you would like to allow **Ctrl-Space** for `<denite:toggle_select_up>` among Vim, Neovim, and Gvim, you have to do

```vim
call denite#custom#map('insert', '<C-@>', '<denite:toggle_select_up>', 'noremap')
call denite#custom#map('insert', '<C-Space>', '<denite:toggle_select_up>', 'noremap')
```

And have to forget about `<C-S-Space>` while Vim/Neovim cannot distinguish `<C-S-Space>` with `<C-@>` or `<C-Space>`

**Comment by petobens** [comment]
Thank you!
