### ISSUE TITLE
Possible to add delete action to buffer kind?

### ISSUE THREAD

**Issue by ragnese** [Shougo/denite.nvim#182]
# Problems summary

This isn't a bug. Just a feature request. When I issue :Denite buffer, I'd like to be able to delete/close
buffers in the list. I think the Unite has this feature.

**Comment by ragnese** [comment]
Thank you! It works exactly as I expected.

**Comment by ervasive** [comment]
It's a bit buggy for me. Sometimes it just doesn't work, other times I get exceptions. Here is the example output:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 119, in start
[denite]     status = self._prompt.start()
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 182, in start
[denite]     raise e
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 172, in start
[denite]     callback=self.on_harvest,
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/prompt.py", line 98, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/action.py", line 15, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 508, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 220, in do_action
[denite]     return action['func'](context)
[denite]   File "/Users/ruslan/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/kind/buffer.py", line 27, in action_delete
[denite]     'bdelete', target['action__bufnr'])
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(wincmd):E16: \xd0\x9d\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbf\xd1\x83\xd1\x81\xd1\x82\xd0\xb8\xd0\xbc\xd1\x8b\xd0\xb9 \xd0\xb4\xd0\xb8\xd0\xb0\xd0\xbf\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xbd: 3wincmd w'
[denite] Please execute :messages command.
```

Setup:
```
NVIM v0.2.0-762-ge32ec03d
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170306-23858-1w3artt/build/config -I/tmp/neovim-20170306-23858-1w3artt/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170306-23858-1w3artt/build/src/nvim/auto -I/tmp/neovim-20170306-23858-1w3artt/build/include
Compiled by ruslan@Ruslans-iMac.Dlink

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e32ec03/share/nvim"
```

**Comment by Shougo** [comment]
I have fixed that.

**Comment by ervasive** [comment]
Thanks, works great for files buffers, although there is some issues when I try to delete Neovim's terminal buffers. I assume that because they are "read only". Anyway here is the exception traceback.

```
[denite] Traceback (most recent call last):
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 119, in start
[denite]     status = self._prompt.start()
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 182, in start
[denite]     raise e
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 172, in start
[denite]     callback=self.on_harvest,
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/prompt.py", line 98, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/action.py", line 15, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 510, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/ruslan/.dotfiles/nvim/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 220, in do_action
[denite]     return action['func'](context)
[denite]   File "/Users/ruslan/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/kind/buffer.py", line 27, in action_delete
[denite]     'bdelete', target['action__bufnr'])
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(bdelete):E89: term://.//7924:/bin/zsh will be killed(add ! to override)'
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
Fixed.
