### ISSUE TITLE
Feature request: quick match

### ISSUE THREAD

**Issue by DerWeh** [Shougo/denite.nvim#259]
Would it be possible to add the quick match mode from `Unite` to `Denite`?

**Comment by Shougo** [comment]
It is on the todo list.

**Comment by yusiwen** [comment]
How to use this quick-move feature? Thanks

**Comment by Shougo** [comment]
Please use `<denite:quick_move>` mapping.
The default is `X` key in normal mode.

**Comment by yusiwen** [comment]
When I press X in normal mode. denite print some errors:
```
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 68, in start
[denite]     self._start(sources, context)
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 131, in _start
[denite]     status = self._prompt.start()
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/prompt.py", line 91, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/action.py", line 328, in _quick_move
[denite]     quick_move_table = get_quick_move_table()
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/action.py", line 304, in get_quick_move_table
[denite]     pos = (base - number) if context['reversed'] else (number + base)
[denite] TypeError: Can't convert 'int' object to str implicitly
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
I cannot reproduce the error.
Please create the new issue with the minimal vimrc and the reproduce ways.

**Comment by yusiwen** [comment]
@Shougo 
My clean vimrc is:
```
set nocompatible

set runtimepath+=/home/yusiwen/.cache/vim2/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('/home/yusiwen/.cache/vim2/dein')
  call dein#begin('/home/yusiwen/.cache/vim2/dein')

  call dein#add('Shougo/dein.vim')
  call dein#add('Shougo/denite.nvim')
  
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

let g:mapleader="\<Space>"
let g:maplocalleader=';'

" INTERFACE
call denite#custom#option('_', {
  \ 'prompt': 'λ:',
  \ 'empty': 0,
  \ 'winheight': 10,
  \ 'short_source_names': 1,
  \ 'vertical_preview': 1,
  \ })

call denite#custom#option('list', {})

" MATCHERS
" Default is 'matcher_fuzzy'
if has('nvim') && &runtimepath =~# '\/cpsm'
  call denite#custom#source(
    \ 'buffer,file_mru,file_old,file_rec,grep,mpc,line',
    \ 'matchers', ['matcher_cpsm', 'matcher_fuzzy'])
endif

" SORTERS
" Default is 'sorter_rank'
call denite#custom#source('z', 'sorters', ['sorter_z'])

" CONVERTERS
" Default is none
call denite#custom#source(
  \ 'buffer,file_mru,file_old',
  \ 'converters', ['converter_relative_word'])

" FIND and GREP COMMANDS
if executable('ag')
  " The Silver Searcher
  call denite#custom#var('file_rec', 'command',
    \ ['ag', '-U', '--hidden', '--follow', '--nocolor', '--nogroup', '-g', ''])

  " Setup ignore patterns in your .agignore file!
  " https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage

  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'default_opts',
    \ [ '--vimgrep', '--smart-case', '--hidden' ])

elseif executable('ack')
  " Ack command
  call denite#custom#var('grep', 'command', ['ack'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--match'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'default_opts',
      \ ['--ackrc', $HOME.'/.config/ackrc', '-H',
      \ '--nopager', '--nocolor', '--nogroup', '--column'])
endif

" KEY MAPPINGS
let insert_mode_mappings = [
  \  ['jj', '<denite:enter_mode:normal>', 'noremap'],
  \  ['<Esc>', '<denite:enter_mode:normal>', 'noremap'],
  \  ['<C-N>', '<denite:assign_next_matched_text>', 'noremap'],
  \  ['<C-P>', '<denite:assign_previous_matched_text>', 'noremap'],
  \  ['<Up>', '<denite:assign_previous_text>', 'noremap'],
  \  ['<Down>', '<denite:assign_next_text>', 'noremap'],
  \  ['<C-Y>', '<denite:redraw>', 'noremap'],
  \ ]

let normal_mode_mappings = [
  \   ["'", '<denite:toggle_select_down>', 'noremap'],
  \   ['<C-n>', '<denite:jump_to_next_source>', 'noremap'],
  \   ['<C-p>', '<denite:jump_to_previous_source>', 'noremap'],
  \   ['gg', '<denite:move_to_first_line>', 'noremap'],
  \   ['st', '<denite:do_action:tabopen>', 'noremap'],
  \   ['sg', '<denite:do_action:vsplit>', 'noremap'],
  \   ['sv', '<denite:do_action:split>', 'noremap'],
  \   ['sc', '<denite:quit>', 'noremap'],
  \   ['r', '<denite:redraw>', 'noremap'],
  \   ['X', '<denite:quick_move>', 'noremap'],
  \ ]

for m in insert_mode_mappings
  call denite#custom#map('insert', m[0], m[1], m[2])
endfor
for m in normal_mode_mappings
  call denite#custom#map('normal', m[0], m[1], m[2])
endfor

nnoremap <silent><LocalLeader>r :<C-u>Denite -resume -refresh<CR>
nnoremap <silent><LocalLeader>f :<C-u>Denite file_rec<CR>
nnoremap <silent><LocalLeader>b :<C-u>Denite buffer file_old -default-action=switch<CR>
nnoremap <silent><LocalLeader>d :<C-u>Denite directory_rec -default-action=cd<CR>
nnoremap <silent><LocalLeader>v :<C-u>Denite register -buffer-name=register<CR>
xnoremap <silent><LocalLeader>v :<C-u>Denite register -buffer-name=register -default-action=replace<CR>
nnoremap <silent><LocalLeader>l :<C-u>Denite location_list -buffer-name=list<CR>
nnoremap <silent><LocalLeader>q :<C-u>Denite quickfix -buffer-name=list<CR>
nnoremap <silent><LocalLeader>n :<C-u>Denite dein<CR>
nnoremap <silent><LocalLeader>g :<C-u>Denite grep<CR>
nnoremap <silent><LocalLeader>j :<C-u>Denite jump change file_point<CR>
nnoremap <silent><LocalLeader>o :<C-u>Denite outline<CR>
```

It has just dein & Denite installed, and 'X' in the normal mode in Denite buffer throws error shown in the previous post.

**Comment by yusiwen** [comment]
BTW, my vim is:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35)
Included patches: 1-95
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-8krYYf/vim-8.0.0095=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.24/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     
```

**Comment by Shougo** [comment]
I cannot reproduce the error.
I think it depends on your configration.

Please test the below.

```vim
set rtp+={path to deoplete}
```

* `:Denite file`
* Press `<C-o>`
* Press `X`

I cannot reproduce the error.

So, please provide the reproduce ways.
Can you understand?

**Comment by Shougo** [comment]
Fixed.
It is only available in Vim8 environment.

**Comment by yusiwen** [comment]
@Shougo 
Yes, this problem only occurs on Vim8. On NeoVim, it's gone.
