### ISSUE TITLE
Define custom action

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#270]
With Unite I use:
```vim
" Custom split action
let s:my_split = {'is_selectable': 1}
function! s:my_split.func(candidate)
    let split_action = 'vsplit'
    if winwidth(winnr('#')) <= 2 * (&tw ? &tw : 80)
        let split_action = 'split'
    endif
    call unite#take_action(split_action, a:candidate)
endfunction
call unite#custom_action('openable', 'context_split', s:my_split)
unlet s:my_split
```
and then define mappings that include `-default-action=context_split`.
Can this be done with Denite? (I've read https://github.com/Shougo/denite.nvim/issues/156 but since that issue was closed I was wondering if this was/will be implemented).

**Comment by Shougo** [comment]
`denite#custom#action()` is already on todo list.

**Comment by petobens** [comment]
Ok. Thanks

**Comment by petobens** [comment]
Thanks Shougo. I've read the commit and help but I don't understand how to use with the following case:
```vim
" Custom split action
let s:my_split = {}
function! s:my_split.func(candidate)
    let split_action = 'vsplit'
    if winwidth(winnr('#')) <= 2 * (&tw ? &tw : 80)
        let split_action = 'split'
    endif
    split_action . ' ' . a:candidate
endfunction
if dein#tap('denite') == 1
    call denite#custom#action('openable', 'context_split', s:my_split)
endif
unlet s:my_split
```
Can you please explain how to do it? Thanks!

**Comment by Shougo** [comment]
```vim
function! s:my_split(context)
    let split_action = 'vsplit'
    if winwidth(winnr('#')) <= 2 * (&tw ? &tw : 80)
        let split_action = 'split'
    endif
    split_action . ' ' . context['targets'][0].action__path
endfunction
call denite#custom#action('file', 'context_split', s:my_split)
```

**Comment by petobens** [comment]
@Shougo with your snippet I get: `Undefined variable: s:my_split`. 
If I add `let s:my_split = {}` then I get
```

E325: ATTENTION
"~/git-repos/private/dotfiles/vimrc" 2525L, 79581C
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 65, in start
[denite]     self._start(sources, context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 131, in _start
[denite]     status = self._prompt.start()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 189, in start
[denite]     raise e
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 179, in start
[denite]     callback=self.on_harvest,
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/prompt.py", line 92, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/action.py", line 19, in _choose_action
[denite]     return prompt.denite.choose_action()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 596, in choose_action
[denite]     return self.do_action(action)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 566, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 257, in do_action
[denite]     action['kind'], action['name'], context)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(call):E731: using Dictionary as a String'
[denite] Please execute :messages command.
````

**Comment by Shougo** [comment]
```vim
call denite#custom#action('file', 'context_split', function('s:my_split'))
```

**Comment by petobens** [comment]
Thank you. Just for completion, the working version is:

```vim
function! s:my_split(context)
    let split_action = 'vsplit'
    if winwidth(winnr('#')) <= 2 * (&tw ? &tw : 80)
        let split_action = 'split'
    endif
    execute split_action . ' ' . a:context['targets'][0].action__path
endfunction
if dein#tap('denite') == 1
    call denite#custom#action('file', 'context_split', function('s:my_split'))
endif
```

**Comment by Shougo** [comment]
I will add the example later.

**Comment by petobens** [comment]
Ok thanks. One last question: why can't I use the action with the buffer (and file) source? I tried changing the kind to `openable` but when I run `Denite buffer` the action is not available.
I want to use this custom action for both `files` and `buffer` sources.

**Comment by petobens** [comment]
Also the `a:context['targets'][0].action__path` is a bit convoluted. Mmmm unite had a nice `take_action` function that avoided doing this.

**Comment by Shougo** [comment]
> One last question: why can't I use the action with the buffer (and file) source?

The buffer source generates buffer kind candidates.
The file source generates file and directory kinds candidates.

```vim
call denite#custom#action('buffer,directory,file', 'context_split', function('s:my_split'))
```

> Also the `a:context['targets'][0].action__path` is a bit convoluted. Mmmm unite had a nice take_action function that avoided doing this.

`take_action()` is not implemented in denite.

**Comment by petobens** [comment]
```
call denite#custom#action('buffer,directory,file', 'context_split', function('s:my_split'))
```
i) the docs simply state `Define {name} action for {kind}.` thus i didn't know you could pass a list.
ii) Your solution does not work with a candidate in a buffer source. It gives the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 65, in start
[denite]     self._start(sources, context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 131, in _start
[denite]     status = self._prompt.start()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 189, in start
[denite]     raise e
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 179, in start
[denite]     callback=self.on_harvest,
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/prompt.py", line 92, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/action.py", line 19, in _choose_action
[denite]     return prompt.denite.choose_action()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 596, in choose_action
[denite]     return self.do_action(action)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 566, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 257, in do_action
[denite]     action['kind'], action['name'], context)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(execute):E716: Key not present in Dictionary: action__path'
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
> i) the docs simply state Define {name} action for {kind}. thus i didn't know you could pass a list.

Yes.  I should fix the doc.

> ii) Your solution does not work with a candidate in a buffer source. It gives the following error:

```vim
function! s:my_split(context)
    let split_action = 'vsplit'
    if winwidth(winnr('#')) <= 2 * (&tw ? &tw : 80)
        let split_action = 'split'
    endif
    if a:context['targets'][0].kind ==# 'buffer'
            execute split_action
            execute 'buffer' a:context['targets'][0].action__bufnr
    else
            execute split_action a:context['targets'][0].action__path
    endif
path
endfunction
```

**Comment by petobens** [comment]
Mmm almost there but:
```
[denite] neovim.api.nvim.NvimError: b"Vim(if):E716: Key not present in Dictionary: kind ==# 'buffer'"
```
Isn't it better to implement a `take_action` function? (it would avoid using the conditional and the dictionary indexing)

**Comment by Shougo** [comment]
```vim
function! s:my_split(context)
    let split_action = 'vsplit'
    if winwidth(winnr('#')) <= 2 * (&tw ? &tw : 80)
        let split_action = 'split'
    endif
    if has_key(a:context['targets'][0], 'action__bufnr')
            execute split_action
            execute 'buffer' a:context['targets'][0].action__bufnr
    else
            execute split_action a:context['targets'][0].action__path
    endif
endfunction
```

> Isn't it better to implement a take_action function? (it would avoid using the conditional and the dictionary indexing)

It is hard.  Because denite is Python3.  The custom action cannot call denite builtin actions directly.

**Comment by petobens** [comment]
Ok. Thank you!!

**Comment by Shougo** [comment]
Related issue.

https://github.com/Shougo/denite.nvim/issues/302
