### ISSUE TITLE
No warning if user-defined command raises an error

### ISSUE THREAD

**Issue by languitar** [Shougo/denite.nvim#275]
# Problems summary

When configuring the command to be called by `file_rec` or `grep`, Denite does not report an error that the configured command might generate. If the binary to call does not exist, the error is reported, however, if the called command returns non-zero (for instance because of wrong command line arguments), only an empty result list is show.

## Expected

In all error cases, Denite reports the problem to the user

## Environment Information (Required!)

 * denite version(SHA1): 99f94a9b010e2225f899bd52ac9f0ae80fe668dd

 * OS: archlinux 64

 * Vim/neovim version:

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```

 * `:CheckHealth` result(neovim only):

```

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  - INFO: Host: /usr/bin/neovim-ruby-host
  - ERROR: Command error (11) /usr/bin/neovim-ruby-host --version: /usr/lib/ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'msgpack' (~> 1.0) among 75 total gem(s) (Gem::MissingSpecError)Checked in 'GEM_PATH=/home/languitar/.gem/ruby/2.4.0:/usr/lib/ruby/gems/2.4.0', execute `gem env` for more information	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1442:in `block in activate_dependencies'	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1431:in `each'	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1431:in `activate_dependencies'	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1413:in `activate'	from /usr/lib/ruby/2.4.0/rubygems.rb:299:in `block in activate_bin_path'	from /usr/lib/ruby/2.4.0/rubygems.rb:299:in `synchronize'	from /usr/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'	from /usr/bin/neovim-ruby-host:22:in `<main>'
  - ERROR: Failed to run: /usr/bin/neovim-ruby-host --version
    - SUGGESTIONS:
      - Report this issue with the output of: 
      - /usr/bin/neovim-ruby-host --version
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
filetype off

call plug#begin('~/.local/share/nvim/bundle/')
Plug 'Shougo/denite.nvim'
call plug#end()

filetype plugin indent on

call denite#custom#var('file_rec/git', 'command',
    \ ['git', 'notexisting-subcommand', '-co', '--exclude-standard']) " see here!
```

## The reproduce ways from neovim starting (Required!)

 1. `nvim -u that-config.ini`
 2.  `:Denite file_rec/git`

## Screen shot (if possible)

![denite](https://cloud.githubusercontent.com/assets/1336287/25989816/def71f60-36fd-11e7-973b-55d419391929.png)

**Comment by Shougo** [comment]
OK.  I will fix it later.

**Comment by Shougo** [comment]
Fixed
