### ISSUE TITLE
window layout not correctly restored with vsplit and quickfix window

### ISSUE THREAD

**Issue by languitar** [Shougo/denite.nvim#279]
# Problems summary

As a follow up of #253 and #276, I am still experiencing issues with restoring the window layout when using splits and the quickfix window.

## Expected

All windows are restored.

## Environment Information (Required!)

 * denite version(SHA1): 99f94a9b010e2225f899bd52ac9f0ae80fe668dd

 * OS: archlinux 64 bit

 * Vim/neovim version: 

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

 * `:CheckHealth` result(neovim only):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  - INFO: Host: /usr/bin/neovim-ruby-host
  - ERROR: Command error (12) /usr/bin/neovim-ruby-host --version: /usr/lib/ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'msgpack' (~> 1.0) among 75 total gem(s) (Gem::MissingSpecError)Checked in 'GEM_PATH=/home/languitar/.gem/ruby/2.4.0:/usr/lib/ruby/gems/2.4.0', execute `gem env` for more information	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1442:in `block in activate_dependencies'	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1431:in `each'	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1431:in `activate_dependencies'	from /usr/lib/ruby/2.4.0/rubygems/specification.rb:1413:in `activate'	from /usr/lib/ruby/2.4.0/rubygems.rb:299:in `block in activate_bin_path'	from /usr/lib/ruby/2.4.0/rubygems.rb:299:in `synchronize'	from /usr/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'	from /usr/bin/neovim-ruby-host:22:in `<main>'
  - ERROR: Failed to run: /usr/bin/neovim-ruby-host --version
    - SUGGESTIONS:
      - Report this issue with the output of: 
      - /usr/bin/neovim-ruby-host --version
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible

set runtimepath+=~/.local/share/nvim/bundle/denite.nvim
```

## The reproduce ways from neovim starting (Required!)

 1. `:copen`
 1. `C-w` `k`
 1. `:vsplit`
 1. `:Denite file_rec`
 1. Press Escape

## Screen shot (if possible)

![denite-restore](https://cloud.githubusercontent.com/assets/1336287/26300789/6d090b2c-3edf-11e7-8578-7ed5706394d9.gif)

**Comment by Shougo** [comment]
I cannot reproduce it...

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/denite.nvim
" set rtp+=~/src/vim-airline/

filetype plugin indent on
syntax enable


nnoremap <silent> ff :<C-u>Denite file_rec<CR>

copen
wincmd k
vsplit
```

**Comment by Shougo** [comment]
I get it.
Your denite.nvim is not the latest.

> denite version(SHA1): 99f94a9

**Comment by languitar** [comment]
Well, but I am obviously seeing this problem. I just used your config file, started `:Denite file_rec` and pressed Escape. Afterwards, the quickfix window stays open.

**Comment by Shougo** [comment]
Please use the latest denite.nvim.
If I remove `winrestcmd` in denite.nvim, the problem occured.
So the feature works.

**Comment by languitar** [comment]
Weird. I definitely pulled today and there were no changes. Now there are and everything works.
