### ISSUE TITLE
Can't exec because of `Unknown function: getwininfo`

### ISSUE THREAD

**Issue by akahana-1** [Shougo/denite.nvim#281]
# Problems summary
When executing `:Denite file_rec`, I get the following error instead:

```
[denite] Traceback (most recent call last):
[denite]   File "/home/um-akahana/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/home/um-akahana/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start(sources, context)
[denite]   File "/home/um-akahana/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 117, in _start
[denite]     self.init_buffer()
[denite]   File "/home/um-akahana/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 140, in init_buffer
[denite]     self._prev_wininfo = self._get_wininfo()
[denite]   File "/home/um-akahana/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 222, in _get_wininfo
[denite]     wininfo = self._vim.call('getwininfo', self._vim.call('win_getid'))[0]
[denite]   File "/home/um-akahana/.pyenv/versions/neovim3/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/home/um-akahana/.pyenv/versions/neovim3/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/home/um-akahana/.pyenv/versions/neovim3/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim:E117: Unknown function: getwininfo'
[denite] Please execute :messages command.
```

## Environment Information

 * denite version(SHA1):
[`37093d1`](https://github.com/Shougo/denite.nvim/commit/37093d182d081fcbdb2ed2a6b4177b2be2527348)

 * OS:
Ubuntu 16.04.2 LTS

 * Vim/neovim version:
NVIM v0.1.7 [`0542baa`](https://github.com/neovim/neovim/commit/0542baac28681050483c685c79efcb4d3c1e32ea)

 * `:CheckHealth` result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - SUGGESTIONS:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - See https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

## tmux
  - SUCCESS: escape-time: 1ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/home/um-akahana/.pyenv/libexec/pyenv"
  - WARNING: pyenv is not set up optimally.
    - SUGGESTIONS:
      - Suggestion: Create a virtualenv specifically for Neovim using pyenv and use "g:python_host_prog".  This will avoid the need to install Neovim's Python client in each version/virtualenv.
  - INFO: Executable: /usr/bin/python2
  - ERROR: Command error (4) /usr/bin/python2 -c import neovim; print(neovim.__file__): Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: unable to find nvim executable
  - ERROR: Neovim Python client is not installed.
    - SUGGESTIONS:
      - Error found was: unable to find nvim executable
      - Use the command `$ pip2 install neovim`
  - WARNING: Latest python2-neovim is NOT installed: 0.1.13

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/home/um-akahana/.pyenv/versions/neovim3/bin/python"
  - INFO: Executable: /home/um-akahana/.pyenv/versions/neovim3/bin/python
  - INFO: Python3 version: 3.5.0
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
execute 'set runtimepath^=' . expand('~/.cache/dein/repos/github.com/Shougo/denite.nvim')
" Neovim python settings
let g:python3_host_prog = $PYENV_ROOT . "/versions/neovim3/bin/python"
filetype plugin on
```

## The reproduce ways from neovim starting (Required!)

Using above `init.vim`, this problem reproduced by following command after executing neovim
```
:Denite file_rec
```

**Comment by Shougo** [comment]
Please update your neovim to the 0.2.0+.

**Comment by akahana-1** [comment]
I updated my neovim to the 0.2.0+.
This problem is fixed.

Thank you for your recommendation.
I'll close this issue.
