### ISSUE TITLE
UnicodeDecodeError occurs

### ISSUE THREAD

**Issue by asuk502** [Shougo/denite.nvim#283]
# Problems summary
`:Denite outline` causes UnicodeDecodeError under certain conditions

## Environment Information (Required!)

 * denite version(SHA1):
37093d1

 * OS:
Ubuntu 16.10

 * Vim/neovim version:
NVIM v0.2.1-dev
 * :CheckHealth result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the en
  vironment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

## Provide a minimal init.vim with less than 50 lines (Required!)
```vim
let g:python3_host_prog = '/usr/bin/python3'
set runtimepath+=~/.vim/plugged/denite.nvim
```

## The reproduce ways from neovim starting (Required!)
I do not know the detailed condition, but `:Denite outline` causes UnicodeDecodeError in the following file
```go
// main.go

type A struct {
	aaaaaaaaaaaaaa int // ああああああああああああああああああああああああ
}
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please upload the full error messages.

**Comment by asuk502** [comment]
Full error messages are here.
```
[denite] Traceback (most recent call last):
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line
 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", li
ne 63, in start
[denite]     self._start(sources, context)
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", li
ne 111, in _start
[denite]     self.gather_candidates()
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", li
ne 534, in gather_candidates
[denite]     self._denite.gather_candidates(self._context)
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 5
7, in gather_candidates
[denite]     source.context, source)
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 6
6, in _gather_source_candidates
[denite]     candidates = source.gather_candidates(context)
[denite]   File "/home/user/.vim/plugged/denite.nvim/rplugin/python3/denite/source/outline.py"
, line 65, in gather_candidates
[denite]     for line in f:
[denite]   File "/usr/lib/python3.5/codecs.py", line 321, in decode
[denite]     (result, consumed) = self._buffer_decode(data, self.errors, final)
[denite] UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 568-569: invalid cont
inuation byte
[denite] Please execute :messages command.
```

**Comment by asuk502** [comment]
Sorry, this error occurs only with the universal-ctags (https://github.com/universal-ctags/ctags).

Apparently, this is not denite's bug.
