### ISSUE TITLE
Couldn't work after installed

### ISSUE THREAD

**Issue by blurm** [Shougo/denite.nvim#296]
# Problems summary
Run`Denite file` this error came out
```
AttributeError: 'NoneType' object has no attribute 'filter' 
```

## Environment Information (Required!)

 * denite version(SHA1): 91431d1

 * OS:Ubuntu 16.04

 * Vim/neovim version: neovim 0.1.7

 * `:CheckHealth` result(neovim only):
```markdown
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - INFO: Build type: None
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - SUGGESTIONS:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - See https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
    " Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
    call plug#begin('~/.vim/plugged')

        " Autocomplete
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'Shougo/denite.nvim'
```

## The reproduce ways from neovim starting (Required!)

 1. Add `Plug 'Shougo/denite.nvim'` in init.vim and reload it
 2. :UpdateRemotePlugins
 3. restart nvim
 4. :Denite file

## Upload the log file
```vim
[denite] Traceback (most recent call last):                                                                                   
[denite]   File "/home/damon/.vim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 33, in start                  
[denite]     return self._uis[buffer_name].start(args[0], args[1])                                                            
[denite]   File "/home/damon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 64, in start                
[denite]     self._start(sources, context)                                                                                    
[denite]   File "/home/damon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 113, in _start              
[denite]     self.update_candidates()                                                                                         
[denite]   File "/home/damon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 305, in update_candidates   
[denite]     self._candidates = self._denite.get_filter(sorter).filter(ctx)                                                   
[denite] AttributeError: 'NoneType' object has no attribute 'filter'                                                          
[denite] Please execute :messages command.     
```

**Comment by rafi** [comment]
PR #295 fixes this error.
