### ISSUE TITLE
The new split setting causes error when set to no

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/denite.nvim#346]
# Problems summary
I'm trying to use the new `split` feature, and I want to set it to `no` since I like to search __in__ the buffer that will open the file I select. But when I do I'm getting python errors.

## Expected
There is no split, and denite simply opens in the buffer I'm currently in.

## Environment Information (Required!)

 * denite version(SHA1): 4eb9724ca004e441987b1833d882d6355019ab4f

 * OS: `Ubuntu 16.04.2 LTS`

 * Vim/neovim version: `NVIM v0.2.1-dev`

 * `:CheckHealth` result:
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=/home/me/.config/nvim/bundle/denite.nvim
nnoremap <c-i> :Denite file_rec -split=no<CR>
```

## The reproduce ways from neovim starting (Required!)

 1. `nvim -u test.vim`
 2. Do `<c-i>`
 3. Try to select a file with `<cr>` or to leave search with `<esc>`.
 4. See the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])                                                                                           
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 68, in start
[denite]     self._start(sources, context)                                                                                                 
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 129, in _start
[denite]     status = self._prompt.start()                                                                                                   
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,                                                                                                   
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/prompt.py", line 91, in on_keypress
[denite]     return self.action.call(self, m.group('action'))                                                                                   
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)                                                                                                        
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/action.py", line 142, in _leave_mode
[denite]     return prompt.denite.leave_mode()                                                                                                   
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 897, in leave_mode
[denite]     return self.quit()                                                                                                                  
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 609, in quit
[denite]     self.quit_buffer()                                                                                                            
[denite]   File "/home/me/dotfiles/.config/nvim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 565, in quit_buffer
[denite]     self._vim.current.window.options.update(self._save_window_options)                                                                   
[denite] AttributeError: 'RemoteMap' object has no attribute 'update'          
[denite] Please execute :messages command
```
## Screen shot (if possible)
![nvim_denite_fail](https://user-images.githubusercontent.com/2212681/28744028-372082c8-7450-11e7-9d9b-07644551aa40.png)

## Upload the log file
[profile.txt](https://github.com/Shougo/denite.nvim/files/1184865/profile.txt)

**Comment by Shougo** [comment]
Reproduced.
