### ISSUE TITLE
No module named `shlex` after python upgrade

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#374]
I update to python 3.6.3 today and i'm getting the following error whenever I execute a denite/deoplete source:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 68, in start
[denite]     self._start(sources, context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 114, in _start
[denite]     self.init_denite()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 633, in init_denite
[denite]     self._denite.start(self._context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 36, in start
[denite]     self.load_sources(context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 204, in load_sources
[denite]     'denite.source.' + name, path).load_module()
[denite]   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
[denite]   File "<frozen importlib._bootstrap_external>", line 823, in load_module
[denite]   File "<frozen importlib._bootstrap_external>", line 682, in load_module
[denite]   File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
[denite]   File "<frozen importlib._bootstrap>", line 675, in _load
[denite]   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
[denite]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[denite]   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
[denite]   File "/Users/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/source/grep.py", line 7, in <module>
[denite]     import shlex
[denite] ModuleNotFoundError: No module named 'shlex'
[denite] Please execute :messages command.
```

**Comment by petobens** [comment]
Reinstall both denite and deoplete fixed it. Sorry for the noise.
