### ISSUE TITLE
"Missing endif" menu error

### ISSUE THREAD

**Issue by ethan-eb** [Shougo/denite.nvim#39]
# Problems summary
When accessing menus, starting with `:Denite menu` I receive "missing endif" error output, and also performs the expected action. However if I start with `:Denite menu:edits` (for example) I do not see the error

## Expected
Expect it to work without error output

## Environment Information

 * OS: OS X 10.11.6 El Capitan

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
```
https://github.com/tweekmonster/nvim-python-doctor
health#nvim#check
================================================================================

## Remote Plugins
  - SUCCESS: Up to date

## Python 2 provider
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /usr/local/bin/python2 does not have the neovim module installed. See ":help provider-python".
    /usr/local/bin/python2.7 does not have the neovim module installed. See ":help provider-python".
    /usr/bin/python2.6 does not have the neovim module installed. See ":help provider-python".
    /usr/local/bin/python does not have the neovim module installed. See ":help provider-python".
  - ERROR: Python provider error
      - SUGGESTIONS:
        - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the neovim module installed. See ":help provider-python".
          /usr/local/bin/python2.7 does not have the neovim module installed. See ":help provider-python".
          /usr/bin/python2.6 does not have the neovim module installed. See ":help provider-python".
          /usr/local/bin/python does not have the neovim module installed. See ":help provider-python".
  - INFO: Executable: Not found

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim Version: 0.1.10
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Ruby provider
  - SUCCESS: Found Neovim RubyGem
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  - INFO: Host Executable: /usr/local/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1

```
## Neovim Python Diagnostic

- Neovim Version: NVIM 0.1.5

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
Plug 'Shougo/denite.nvim'
Plug 'Shougo/neoyank.vim'

:nmap <Leader>m :Denite menu<CR>
let s:menus = {}
let s:menus.edits = {'description': 'Common edit targets'}
let s:menus.edits.file_candidates = [
    \ ['nvim init.vim', '~/.config/nvim/init.vim'],
    \ ['bashrc', '~/.bashrc'],
    \ ['bash aliases', '~/.bash_aliases'],
    \ ['eb aliases', '~/.eb_aliases'],
    \ ['profile', '~/.profile'],
    \ ]
call denite#custom#var('menu', 'menus', s:menus)

```

## The reproduce ways from neovim starting (Required!)

 1. Start neovim
 2. Hit `<leader>m`
 3. Select "edits"
 4. Select "nvim init.vim"
 5. init.vim opens for editing, but also see this ouput:
```
Error detected while processing function denite#helper#call_denite[12]..denite#start[10].._denite_start:
line    1:
[denite] Traceback (most recent call last):
[denite]   File "/Users/ethan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 64, in start
[denite]     self.input_loop()
[denite]   File "/Users/ethan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 228, in input_loop
[denite]     ret = func() if len(map_args) == 1 else func(arg)
[denite]   File "/Users/ethan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 275, in do_action
[denite]     self.quit_buffer()
[denite]   File "/Users/ethan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 165, in quit_buffer
[denite]     self.__vim.command('silent bdelete! ' + str(self.__bufnr))
[denite]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 216, in command
[denite]     return self.request('vim_command', string, **kwargs)
[denite]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(bdelete):E516: No buffers were deleted: silent bdelete! 2'
[denite] An error has occurred. Please execute :messages command.
Error detected while processing function denite#helper#call_denite[12]..denite#start:
line   10:
E171: Missing :endif
Press ENTER or type command to continue
```

### HOWEVER, this works without error:

 1. start nvim
 2. Enter `:Denite menu:edits`
 3. Select "nvim init.vim"
 4. File opens, no problem

**Comment by Shougo** [comment]
Fixed
