### ISSUE TITLE
Crashes when fed bad data

### ISSUE THREAD

**Issue by glacambre** [Shougo/denite.nvim#412]
# Problems summary
I don't know how it happened, but the following line managed to find its way in my `~/.cache/neomru/file` file.
```
man://index.(bt|db|dir|pag)^@              An FHS compliant global index database cache.^@^@SEE ALSO^@       apropos(1) , groff(1), less(1), manpath(1), nroff(1),  troff(1),  whatis(1),  zsoelim(1),  setlo‐^@       cale(3),  manpath(5),  a scii(7), latin1(7), man(7), catman(8), mandb(8), the man-db package man‐^@       ual, FSSTND^@^@HISTORY^@       1990, 1 991 – Originally written by John W. Eaton (jwe@che.utexas.edu).^@^@       Dec 23 1992:  Rik  Faith  (faith@cs.unc.edu) applied  bug  fixes  supplied  by  Willem  Kasdorp^@       (wkasdo@nikhefk.nikef.nl).^@^@       30th  April 1994 – 23r d February 2000: Wilf. (G.Wilford@ee.surrey.ac.uk) has been developing and^@       maintaining this package with the he lp of a few dedicated people.^@^@       30th October 1996 – 30th March  2001:  Fabrizio  Polacco  <fpolacco@debian.org> maintained  and^@       enhanced this package for the Debian project, with the help of all the community.^@^@       3 1st  March  2001  – present day: Colin Watson <cjwatson@debian.org> is now developing and main‐^@       taining man-db. ^@^@2.7.6(1                                        2016-12-12                                        MAN(1))
```
Because of that, Denite `Denite file_mru` crashed with the following error message from time to time:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 70, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 135, in _start
[denite]     status = self._prompt.start()
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 201, in start
[denite]     raise e
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keymap.py", line 337, in harvest
[denite]     interval=interval,
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/keymap.py", line 387, in _getcode
[denite]     callback()
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/prompt.py", line 74, in on_harvest
[denite]     self.denite.update_buffer()
[denite]   File "/home/me/.dotfiles/default/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 404, in update_buffer
[denite]     self._vim.current.buffer[:] = self._displayed_texts
[denite]   File "/usr/lib64/python3.4/site-packages/neovim/api/buffer.py", line 71, in __setitem__
[denite]     True, include_end, lines)
[denite]   File "/usr/lib64/python3.4/site-packages/neovim/api/nvim.py", line 129, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/lib64/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'String cannot contain newlines'
[denite] Please execute :messages command.
```
Once I removed the offending line, Denite stopped crashing.

I don't know how to reproduce the `man://...` line ending up in my mru file but manually appending the line will let you reproduce the crash consistently.

## Environment Information (Required!)
 * denite version(SHA1): d09cfdf1ebdfe8257259a7d6f9796fcbb9228d26
 * OS: Linux 4.12.5-gentoo
 * Vim/neovim version: NVIM v0.2.3-394-g4fedad6c5
 * `:checkhealth` or `:CheckHealth` result(neovim only): Everything seems fine.

**Comment by Shougo** [comment]
It is the feature.
Please don't add the bad line.

**Comment by glacambre** [comment]
I wasn't responsible for the bad line being added to my cache, neomru was. Should I file a bug in neomru's repos? I don't know how to reproduce the this bug.

**Comment by Shougo** [comment]
I don't know why it is generated.
If you can reproduce the problem, it is neomru's issue.
