### ISSUE TITLE
Undefined variable: b:denite_context

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#439]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

`b:denite_context` variable does not exist in `expr` map function.

## Expected

Be able to access the context from a user function.

## Environment Information (Required!)

 * denite version(SHA1): bd88b367f6d159dfd685e1088dfbfd9f83d63e04

 * OS: macOS

 * Vim/neovim version: neovim

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=/Users/jniehus/Downloads/dev/denite.nvim
function! ToggleSorter(sorter) abort
    let l:sorters = split(b:denite_context.sorters, ',')
    if index(l:sorters, a:sorter) == -1
        call add(l:sorters, a:sorter)
    else
        call remove(l:sorters, index(l:sorters, a:sorter))
    endif
    let b:denite_context.sorters = join(l:sorters, ',')
    return '<denite:redraw>'
endfunction
call denite#custom#map('insert', '<C-f>',
    \ 'ToggleSorter("sorter_ftime")', 'noremap expr nowait')
```

## The reproduce ways from neovim starting (Required!)

 1. Open `:Denite file`.
2. Press `<C-f>` to attempt to toggle `sorter_ftime`.

The full error:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 136, in _start
[denite]     status = self._prompt.start()
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 201, in start
[denite]     raise e
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/prompt/keymap.py", line 346, in harvest
[denite]     keystroke = self.resolve(nvim, previous, nowait=False)
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/prompt/keymap.py", line 284, in resolve
[denite]     return self._resolve(nvim, definition)
[denite]   File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/denite.nvim/rplugin/python3/denite/prompt/keymap.py", line 299, in _resolve
[denite]     rhs = Keystroke.parse(nvim, nvim.eval(definition.rhs))
[denite]   File "/Users/jniehus/Documents/dev/py3.6.2env/lib/python3.6/site-packages/neovim/api/nvim.py", line 226, in eval
[denite]     return self.request('nvim_eval', string, **kwargs)
[denite]   File "/Users/jniehus/Documents/dev/py3.6.2env/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/Users/jniehus/Documents/dev/py3.6.2env/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(let):E121: Undefined variable: b:denite_context'
[denite] Please execute :messages command.
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
Please use the patch.

```vim
diff --git a/rplugin/python3/denite/ui/prompt.py b/rplugin/python3/denite/ui/prompt.py
index d73892e..c5f5191 100644
--- a/rplugin/python3/denite/ui/prompt.py
+++ b/rplugin/python3/denite/ui/prompt.py
@@ -1,4 +1,4 @@
-from copy import copy
+from copy import deepcopy
 from .action import DEFAULT_ACTION_RULES
 from datetime import timedelta, datetime
 from ..prompt.prompt import (
@@ -63,6 +63,9 @@ class DenitePrompt(Prompt):
         return super().on_update(status)

     def on_harvest(self):
+        # Set b:denite_context
+        self.denite._bufvars['denite_context'] = self.context
+
         if self._timeout > datetime.now():
             return

@@ -91,13 +94,15 @@ class DenitePrompt(Prompt):

         m = ACTION_KEYSTROKE_PATTERN.match(str(keystroke))
         if m:
-            bufvars = self.denite._bufvars
-            bufvars['denite_context'] = self.context
-            prev_context = copy(self.context)
             ret = self.action.call(self, m.group('action'))
-            if bufvars['denite_context'] != prev_context:
+
+            bufvars = self.denite._bufvars
+            if ('denite_new_context' in bufvars
+                    and bufvars['denite_new_context']):
                 # Update context
-                self.context = bufvars['denite_context']
+                self.context.update(bufvars['denite_new_context'])
+                bufvars['denite_new_context'] = {}
+
             return ret
         elif self.denite.current_mode == 'insert':
             # Updating text from a keystroke is a feature of 'insert' mode
shougo% git diff
diff --git a/rplugin/python3/denite/ui/prompt.py b/rplugin/python3/denite/ui/prompt.py
index d73892e..532a5e6 100644
--- a/rplugin/python3/denite/ui/prompt.py
+++ b/rplugin/python3/denite/ui/prompt.py
@@ -1,4 +1,3 @@
-from copy import copy
 from .action import DEFAULT_ACTION_RULES
 from datetime import timedelta, datetime
 from ..prompt.prompt import (
@@ -63,6 +62,9 @@ class DenitePrompt(Prompt):
         return super().on_update(status)

     def on_harvest(self):
+        # Set b:denite_context
+        self.denite._bufvars['denite_context'] = self.context
+
         if self._timeout > datetime.now():
             return

@@ -91,13 +93,15 @@ class DenitePrompt(Prompt):

         m = ACTION_KEYSTROKE_PATTERN.match(str(keystroke))
         if m:
-            bufvars = self.denite._bufvars
-            bufvars['denite_context'] = self.context
-            prev_context = copy(self.context)
             ret = self.action.call(self, m.group('action'))
-            if bufvars['denite_context'] != prev_context:
+
+            bufvars = self.denite._bufvars
+            if ('denite_new_context' in bufvars
+                    and bufvars['denite_new_context']):
                 # Update context
-                self.context = bufvars['denite_context']
+                self.context.update(bufvars['denite_new_context'])
+                bufvars['denite_new_context'] = {}
+
             return ret
         elif self.denite.current_mode == 'insert':
             # Updating text from a keystroke is a feature of 'insert' mode
```

**Comment by Shougo** [comment]
And please use `b:denite_new_context` instead.

```vim
function! ToggleSorter(sorter) abort
    let l:sorters = split(b:denite_context.sorters, ',')
    if index(l:sorters, a:sorter) == -1
        call add(l:sorters, a:sorter)
    else
        call remove(l:sorters, index(l:sorters, a:sorter))
    endif
    let b:denite_new_context = {}
    let b:denite_new_context.sorters = join(l:sorters, ',')
    return '<denite:redraw>'
endfunction
call denite#custom#map('insert', '<C-f>',
    \ 'ToggleSorter("sorter_reverse")', 'noremap expr nowait')
```

**Comment by Shougo** [comment]
I will update the documentation later.

**Comment by wilywampa** [comment]
That almost works, but the new sorters don't take effect (modify the order of visible candidates) until after pressing the mapping multiple times.

**Comment by Shougo** [comment]
Unfortunately, the sorter change is affected after `<denite:redraw>`.

**Comment by Shougo** [comment]
I think it is better behavior.

```vim
diff --git a/rplugin/python3/denite/ui/prompt.py b/rplugin/python3/denite/ui/prompt.py
index d73892e..bec9101 100644
--- a/rplugin/python3/denite/ui/prompt.py
+++ b/rplugin/python3/denite/ui/prompt.py
@@ -1,4 +1,3 @@
-from copy import copy
 from .action import DEFAULT_ACTION_RULES
 from datetime import timedelta, datetime
 from ..prompt.prompt import (
@@ -63,6 +62,9 @@ class DenitePrompt(Prompt):
         return super().on_update(status)

     def on_harvest(self):
+        # Set b:denite_context
+        self.denite._bufvars['denite_context'] = self.context
+
         if self._timeout > datetime.now():
             return

@@ -91,13 +93,16 @@ class DenitePrompt(Prompt):

         m = ACTION_KEYSTROKE_PATTERN.match(str(keystroke))
         if m:
-            bufvars = self.denite._bufvars
-            bufvars['denite_context'] = self.context
-            prev_context = copy(self.context)
             ret = self.action.call(self, m.group('action'))
-            if bufvars['denite_context'] != prev_context:
+
+            bufvars = self.denite._bufvars
+            if ('denite_new_context' in bufvars
+                    and bufvars['denite_new_context']):
                 # Update context
-                self.context = bufvars['denite_context']
+                self.context.update(bufvars['denite_new_context'])
+                bufvars['denite_new_context'] = {}
+                self.denite.redraw()
+
             return ret
         elif self.denite.current_mode == 'insert':
             # Updating text from a keystroke is a feature of 'insert' mode
```

**Comment by Shougo** [comment]
Better version of the sample.

```vim
function! ToggleSorter(sorter) abort
    let sorters = split(b:denite_context.sorters, ',')
    let idx = index(sorters, a:sorter)
    if idx < 0
        call add(sorters, a:sorter)
    else
        call remove(sorters, idx)
    endif
    let b:denite_new_context = {}
    let b:denite_new_context.sorters = join(sorters, ',')
    return '<denite:redraw>'
endfunction
call denite#custom#map('insert', '<C-f>',
    \ 'ToggleSorter("sorter_reverse")', 'noremap expr nowait')
```

I will add the sample in the documentation later.

**Comment by wilywampa** [comment]
Yes, that's better. Thanks!

**Comment by Shougo** [comment]
Fixed.
