### ISSUE TITLE
Action :new is missing

### ISSUE THREAD

**Issue by maxnordlund** [Shougo/denite.nvim#445]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Seems like the `new` action is missing

## Expected

It to open a new buffer with the marked file.

## Environment Information (Required!)

 * denite version(SHA1): f9b0fd585e12faf3f6c1764241839719e60d30b9

 * OS: Mac OSX 10.13.3 (17D47)

 * Vim/neovim version:
    ```
    NVIM v0.2.2
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/config -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/include
    Kompilerad av brew@HighSierra-2.local

    Features: +acl +iconv +jemalloc +tui
    See ":help feature-compile"

       system-vimrc-fil: "$VIM/sysinit.vim"
      reserv för $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

    Run :checkhealth for more info
    ```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

<details>
<summary>`:CheckHealth`</summary>
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: pyenv was found, but $PYENV_ROOT is not set.
    - ADVICE:
      - Did you follow the final install instructions?
      - If you use a shell "framework" like Prezto or Oh My Zsh, try without.
      - Try a different shell (bash).
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.1
  - OK: Latest python2-neovim is installed: 0.2.1

## Python 3 provider (optional)
  - WARNING: pyenv was found, but $PYENV_ROOT is not set.
    - ADVICE:
      - Did you follow the final install instructions?
      - If you use a shell "framework" like Prezto or Oh My Zsh, try without.
      - Try a different shell (bash).
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.1
  - OK: Latest python3-neovim is installed: 0.2.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v9.5.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?
</details>

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. :Denite file_rec " or something similar
 2. <C-o> " to switch to normal mode
 3. n

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
This is what is displayed, and is also the output of :messages
```
[denite] Invalid action: new
[denite] Traceback (most recent call last):
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 136, in _start
[denite]     status = self._prompt.start()
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/prompt.py", line 96, in on_keypress
[denite]     ret = self.action.call(self, m.group('action'))
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/action.py", line 18, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 662, in do_action
[denite]     self._context, action_name, candidates)
[denite]   File "/Users/maxno/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 349, in get_action
[denite]     actions.add(action['name'])
[denite] KeyError: 'name'
[denite] Please execute :messages command.
```

## Upload the log file
https://gist.github.com/maxnordlund/513699a5676ace3ff55222105de1afa4

**Comment by maxnordlund** [comment]
Lovely, thanks. ありがとう
