### ISSUE TITLE
Error when interacting with menus and submenus

### ISSUE THREAD

**Issue by etiennebatise** [Shougo/denite.nvim#46]
# Problems summary
When interacting with submenus, canceling (hitting q in normal mode) or validating (hitting <CR>) on the right item outputs an error message **and** execute the command successfully.

## Expected
There shouldn't be an error.

## Environment Information

 * OS:
Archlinux 4.6.8-1

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

```
## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.6

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim Version: 0.1.10
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim Version: 0.1.10
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  - INFO: Host Executable: /usr/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1


```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/


call dein#begin(expand('~/.config/nvim/dein/'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/denite.nvim')
call dein#end()
filetype plugin indent on       " Indent and plugins by filetype

let s:menus = {}
let s:menus.vim = {
    \ 'description': 'Vim',
    \ }
let s:menus.vim.file_candidates = [
    \ ['    > Edit configuation file (init.vim)', '~/.config/nvim/init.vim']
    \ ]
call denite#custom#var('menu', 'menus', s:menus)

```

## The reproduce ways from neovim starting (Required!)

 1.Open neovim
 2. :Denite menu
 3. <C-o> Enter ("click on vim")
4. Either <C-o> q   OR   <C-o> Enter (Cancel or validate)

Note the openning with :Denite menu:vim does not trigger this error: 
```
Erreur détectée en traitant function denite#helper#call_denite[12]..denite#start[15].._denite_start :
ligne    1 :
[denite] Traceback (most recent call last):
[denite]   File "/home/etienne/.config/nvim/dein/.dein/rplugin/python3/denite/ui/default.py", line 68, in start
[denite]     self.input_loop()
[denite]   File "/home/etienne/.config/nvim/dein/.dein/rplugin/python3/denite/ui/default.py", line 322, in input_loop
[denite]     ret = func() if len(map_args) == 1 else func(arg)
[denite]   File "/home/etienne/.config/nvim/dein/.dein/rplugin/python3/denite/ui/default.py", line 376, in do_action
[denite]     self.quit_buffer()
[denite]   File "/home/etienne/.config/nvim/dein/.dein/rplugin/python3/denite/ui/default.py", line 252, in quit_buffer
[denite]     self.__vim.command('silent bdelete! ' + str(self.__bufnr))
[denite]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 216, in command
[denite]     return self.request('vim_command', string, **kwargs)
[denite]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b"Vim(bdelete):E516: Aucun tampon n'a \xc3\xa9t\xc3\xa9 effac\xc3\xa9: silent bdelete! 2"
[denite] An error has occurred. Please execute :messages command.

``` 

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
[http://pastebin.com/QRHgphgv](http://pastebin.com/QRHgphgv)

**Comment by etiennebatise** [comment]
(Also the description is not displayed)

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
Fixed.
