### ISSUE TITLE
Denite/denite-git/deoplete crash

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#578]
Consider the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/deoplete.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/neoclide/denite-git
filetype plugin indent on

let g:deoplete#enable_at_startup = 1
```
Now:
1. Open nvim in a git repo
2. Run `:Denite -auto-preview gitlog`
3. Press `<ESC>`
I get the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/rplugin.py", line 25, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 76, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 154, in _start
[denite]     status = self._prompt.start()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 201, in start
[denite]     raise e
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/prompt.py", line 96, in on_keypress
[denite]     ret = self.action.call(self, m.group('action'))
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/action.py", line 143, in _leave_mode
[denite]     return prompt.denite.leave_mode()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 1004, in leave_mode
[denite]     return self.quit()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 633, in quit
[denite]     self.quit_buffer()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 608, in quit_buffer
[denite]     self._vim.command(self._winrestcmd)
[denite]   File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
[denite]     return self.request('nvim_command', string, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.nvim.NvimError: b"Vim:error caught in async handler 'deoplete_on_event [{'rpc': 'deoplete_on_event', 'event': 'BufDelete', 'sources': []}]'"
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
What is your environment?
Please don't ignore issue template.

**Comment by petobens** [comment]
I'm on arch linux using `NVIM v0.4.0-276-g6b827bb66`

**Comment by Shougo** [comment]
Really git-log source is needed to reproduce the problem?

**Comment by Shougo** [comment]
I have fixed it in deoplete side.
Please use the latest version of deoplete.

**Comment by petobens** [comment]
Thank you
