### ISSUE TITLE
Python error after ced8777

### ISSUE THREAD

**Issue by raghur** [Shougo/denite.nvim#583]
# Problems summary 
Python error after ced8777.
checking out commit before ced8777 works without error.
```
[denite] Traceback (most recent call last):
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\rplugin.py", line 25, in start
[denite]     return ui.start(args[0], context)
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 76, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 134, in _start
[denite]     self.init_denite()
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 659, in init_denite
[denite]     self._denite.start(self._context)
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\denite.py", line 36, in start
[denite]     self._load_filters(context)
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\denite.py", line 346, in _load_filters
[denite]     for Filter, path, module_path in rplugins:
[denite]   File "C:/Users/raghuramanr/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\util.py", line 246, in import_rplugins
[denite]     spec.loader.exec_module(module)
[denite]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[denite]   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
[denite]   File "c:\users\raghuramanr\appdata\local\nvim\bundle\denite.nvim\rplugin\python3\denite\filter\converter_abbr_word.py", line 2, in <module>
[denite]     from .converter.abbr_word import Filter as Base
[denite] SystemError: Parent module 'denite.filter' not loaded, cannot perform relative import
```

## Expected
no error

## Environment Information (Required!)

 * denite version (SHA1): Any commit after (and including) - ced8777  

 * OS: Win 8.1

 * Vim/neovim version: 0.4.0 (nightly)

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.vim/bundle/denite.nvim/
```

## How to reproduce problems from neovim startup (Required!)
`:Denite file`

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/516267/54009135-aec84500-418f-11e9-81d0-ca9f9f480d3a.png)

**Comment by jdefez** [comment]
+1

**Comment by Shougo** [comment]
@jdefez I don't reproduce the error.
Please remove denite.nvim directory and re-install denite.nvim.

If you can reproduce the error, please upload the error messages like the issue.

If not, I will ignore your report.

**Comment by jdefez** [comment]
I have removed/reinstalled denite and the problem still occurs. I’ll open an another issue with all the details needed. thx
