### ISSUE TITLE
Can not execute action for menu source (vim)

### ISSUE THREAD

**Issue by yuntan** [Shougo/denite.nvim#60]
# Problems summary
I got errors and cannot execute action for selected candidate when I open `Denite menu`.

## Expected
Execute appreciate action.

## Environment Information
* OS: Arch linux
* VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 30 2016 15:27:09)
* denite.nvim d3fa1c4

## Provide a minimal init.vim with less than 50 lines (Required!)
minimal .vimrc

```vim
set runtimepath+=$HOME/.vim/denite.nvim

" Add custom menus
let s:menus = {}

let s:menus.my_commands = {
    \ 'description': 'Example commands'
    \ }
let s:menus.my_commands.command_candidates = [
    \ ['Split the window', 'vnew'],
    \ ['Open zsh menu', 'Denite menu:zsh'],
    \ ]

call denite#custom#var('menu', 'menus', s:menus)
```

### case1
 1. enter cmdline and `Denite menu`
 2. select "my_commands" candidate and hit `<CR>` (expect open `menu:my_commands` source)
 3. get errors

### case 2
1. enter cmdline and `Denite menu:my_commands`
2. select first candidate (expect open new buffer)
3. get errors

```
[denite] Traceback (most recent call last):
[denite]   File "/home/yuntan/.vim/denite.nvim/rplugin/python3/denite/ui/default.py", line 79, in start
[denite]     self.input_loop()
[denite]   File "/home/yuntan/.vim/denite.nvim/rplugin/python3/denite/ui/default.py", line 331, in input_loop
[denite]     ret = func() if len(map_args) == 1 else func(arg)
[denite]   File "/home/yuntan/.vim/denite.nvim/rplugin/python3/denite/ui/default.py", line 375, in do_action
[denite]     self.__context, action, candidates)
[denite]   File "/home/yuntan/.vim/denite.nvim/rplugin/python3/denite/denite.py", line 231, in do_action
[denite]     return func(context)
[denite]   File "/home/yuntan/.vim/denite.nvim/rplugin/python3/denite/kind/file.py", line 22, in action_open
[denite]     path = target['action__path']
[denite] KeyError: 'action__path'
[denite] An error has occurred. Please execute :messages command.
```

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
![161113_133617](https://cloud.githubusercontent.com/assets/574575/20243782/931f56d4-a9a9-11e6-9ada-54af4b4cd5ee.png)

## Upload the log file

# Solution
```diff
diff --git a/rplugin/python3/denite/denite.py b/rplugin/python3/denite/denite.py
index 01b9196..5c02bd8 100644
--- a/rplugin/python3/denite/denite.py
+++ b/rplugin/python3/denite/denite.py
@@ -207,8 +207,11 @@ def load_kinds(self, context):
             self.__kinds[name] = module.Kind(self.__vim)
 
     def do_action(self, context, action_name, targets):
-        if 'kind' in targets:
-            kind_name = targets['kind']
+        # if 'kind' in targets:
+        #     kind_name = targets['kind']
+        if 'kind' in targets[0]:
+            kind_name = targets[0]['kind']
         else:
             kind_name = self.__sources[targets[0]['source']].kind
 ```

This patch fixes my problem.

**Comment by Shougo** [comment]
Thank you.

**Comment by yuntan** [comment]
Problem not solved...

`if 'kind' in targets[0]:` instead `if 'kind' in targets:` fixes this.

**Comment by Shougo** [comment]
Fixed.
