### ISSUE TITLE
NvimError: b'nvim_list_wins not implemented'

### ISSUE THREAD

**Issue by mikelue** [Shougo/denite.nvim#634]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

## Environment Information (Required!)

 * denite version (SHA1): f16b581357a575f37f4c51f6c809e8f2fd98b5bf
 * OS: Windows 10 x64
 * Vim/neovim version: Vim 8.1.1248

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim(vimrc)

" configurations {{{
set autoindent
set autoread
set autowrite

set cmdheight=1

set hlsearch

set foldenable
set foldcolumn=4

set smarttab
set tabstop=4
set shiftwidth=4
set noexpandtab
set fileformats=unix,dos

set previewheight=32

set splitright
" }}}

packadd matchit

set dictionary=~/vimfiles/dictionary/6of12.txt

set wildignore=*/*classes/*,*.class

set nobackup

set undofile

" UTF-8 編碼 {{{
set encoding=utf-8

set t_Co=256
let g:terminal_ansi_colors = ["#1c2023","#c7ae95","#95c7ae","#aec795","#ae95c7","#c795ae","#95aec7","#c7ccd1","#747c84","#c7ae95","#95c7ae","#aec795","#ae95c7","#c795ae","#95aec7","#f3f4f5"]

" }}}

" Denite {{{

" file/rec by find {{{
let findCommand = has("win32") ? "c:/bin/cygwin64/bin/find.exe" : "find"
call denite#custom#var('file/rec', "command", [
	\ findCommand,
	\ '-L', ':directory',
	\ '!', '-name', "'.*'", '-a',
	\ '(',
	\ '-path', '*/target/*', '-prune', '-o',
	\ '-path', "'*/.*'", '-prune', '-o',
	\ '-type', 'l', '-print', '-o',
	\ '-type', 'f', '-print',
	\ ')',
\ ])
" }}}

" grep by Ack {{{
call denite#custom#var('grep', 'command', ["perl", "c:/bin/ack"])
call denite#custom#var('grep', 'default_opts',
		\ ['-H', '-i', '--nopager', '--nocolor', '--nogroup', '--column'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--match'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
" }}}

" }}}

```

## How to reproduce problems from neovim startup (Required!)

 1. `Denite file`
 2. "preview" any file

## Generate a logfile if appropriate
```
[vim-hug-neovim-rpc] rpc method [nvim_list_wins] not implemented in pythonx/neovim_rpc_methods.py. Please send PR or contact the mantainer.

[denite] Traceback (most recent call last):
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\rplugin.py", line 25, in start
[denite]     return ui.start(args[0], context)
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\ui\default.py", line 81, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\ui\default.py", line 159, in _start
[denite]     status = self._prompt.start()
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\prompt\prompt.py", line 201, in start
[denite]     raise e
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\prompt\prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\ui\prompt.py", line 96, in on_keypress
[denite]     ret = self.action.call(self, m.group('action'))
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\prompt\action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\ui\action.py", line 18, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\ui\default.py", line 705, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\parent.py", line 35, in do_action
[denite]     return self._put('do_action', [context, action_name, targets])
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\parent.py", line 53, in _put
[denite]     return self._child.main(name, args, queue_id=None)
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\child.py", line 45, in main
[denite]     ret = self.do_action(args[0], args[1], args[2])
[denite]   File "C:/Users/mike/vimfiles/plugged/denite.nvim/rplugin/python3\denite\child.py", line 214, in do_action
[denite]     return action['func'](context) if action['func'] else self._vim.call(
[denite]   File "c:\users\mike\vimfiles\plugged\denite.nvim\rplugin\python3\denite\kind\file.py", line 46, in action_preview
[denite]     self._get_preview_window() and
[denite]   File "c:\users\mike\vimfiles\plugged\denite.nvim\rplugin\python3\denite\kind\file.py", line 150, in _get_preview_window
[denite]     self.vim.windows), None)
[denite]   File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\pynvim\api\common.py", line 151, in __iter__
[denite]     items = self._fetch()
[denite]   File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\pynvim\api\nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\pynvim\msgpack_rpc\session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.nvim.NvimError: b'nvim_list_wins not implemented'
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
Fixed in the latest version.
