### ISSUE TITLE
python errors triggered

### ISSUE THREAD

**Issue by jdefez** [Shougo/denite.nvim#648]
# Problems summary
Denite  (commit 6937f1d9186a4d464b158368a3f38d9a7c5c14eb) triggers python errors when I run Denite grep ... or DeniteCursorWord

But i also suspect that this problem occured when I had to upgrade to node 12.4.0. Before I upgraded it denite was working fine.

```
[denite] Traceback (most recent call last):
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 26, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 144, in _start_sources_qu
eue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 187, in _start
[denite]     self._init_denite()
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 660, in _init_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 35, in on_init
[denite]     self._put('on_init', [context])
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 62, in _put
[denite]     return self._child.main(name, args, queue_id=None)
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 69, in main
[denite]     self.on_init(args[0])
[denite]   File "/Users/jean/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 129, in on_init
[denite]     raise NameError('Source "' + name + '" is not found.')
[denite] NameError: Source "-mode=normal" is not found.
[denite] Please execute :messages command.
```

```
health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.0

## Node.js provider (optional)
  - INFO: Node.js: v12.4.0
  - INFO: Neovim node.js host: /Users/jean/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```

my [init.vim](https://github.com/jdefez/neovim/blob/26959b68daf998b45ab5b580d92c81f0431c2e03/init.vim#L1) 

```
" denite part in my init.vim

function! s:profile(opts) abort
	for l:fname in keys(a:opts)
		for l:dopt in keys(a:opts[l:fname])
			call denite#custom#option(l:fname, l:dopt, a:opts[l:fname][l:dopt])
		endfor
	endfor
endfunction

call denite#custom#var('file/rec', 'command', ['rg', '--files', '--glob', '!.git'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts', ['--hidden', '--vimgrep', '--heading', '-S'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

let s:denite_options = {'default' : {
\ 'auto_resize': 1,
\ 'prompt': 'λ:',
\ 'direction': 'rightbelow',
\ 'winminheight': '10',
\ 'highlight_mode_insert': 'Visual',
\ 'highlight_mode_normal': 'Visual',
\ 'prompt_highlight': 'Function',
\ 'highlight_matched_char': 'Function',
\ 'highlight_matched_range': 'Normal'
\ }}

call s:profile(s:denite_options)

nnoremap <leader>g :<C-u>Denite grep:. -no-empty -mode=normal<CR>
nnoremap <leader>j :<C-u>DeniteCursorWord grep:. -mode=normal<CR>
```

## Environment Information (Required!)
```
macos: 10.14.5

NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190516-12851-1ltswi2/build/config -I/tmp/neovim-20190516-12851-1ltswi2/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190516-12851-1ltswi2/build/src/nvim/auto -I/tmp/neovim-20190516-12851-1ltswi2/build/include
```

## Screenshot (if possible)
![Capture d’écran 2019-06-05 à 18 34 39](https://user-images.githubusercontent.com/624058/58973593-9d0f3180-87c0-11e9-824b-66c18bf98033.png)

**Comment by dmix** [comment]
Came across the same problem just now when I upgrade SpaceVim, which update denite.nvim

**Comment by Shougo** [comment]
OK.

```vim
nnoremap <leader>g :<C-u>Denite grep:. -no-empty<CR>
nnoremap <leader>j :<C-u>DeniteCursorWord grep:.<CR>
```

`-mode` option is removed in current version.

And the default mappings are removed.
You need to define your mappings like this.

https://github.com/Shougo/denite.nvim#examples

**Comment by jdefez** [comment]
@Shougo thank you very much for your quick answer.

**Comment by ctaylo21** [comment]
If you are going to make breaking changes, can you at least show what the new mappings should look like for the most common examples? LIke `Denite buffer`, `Denite file/rec`, and the two mentioned in this issue? 

Or can I leave some mappings like this:
```
nmap ; :Denite buffer -split=floating -winrow=1<CR>
nmap <leader>t :Denite file/rec -split=floating -winrow=1<CR>
```

**Comment by Shougo** [comment]
> If you are going to make breaking changes, can you at least show what the new mappings should look like for the most common examples? 

It is already described.

https://github.com/Shougo/denite.nvim#examples

**Comment by Shougo** [comment]
> Or can I leave some mappings like this:

It should work.
