### ISSUE TITLE
Some command not working  with neovim floating window

### ISSUE THREAD

**Issue by tracyone** [Shougo/denite.nvim#658]
# Problems summary

Following command not working with neovim's floating window but **work well in split window**

- `:Denite file`

```
[denite] Traceback (most recent call last):
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/rplugin.py", line 26, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 144, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 196, in _start
[denite]     self._init_buffer()
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 221, in _init_buffer
[denite]     self._resize_buffer()
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 535, in _resize_buffer
[denite]     {'height': winheight})
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.nvim.NvimError: b'Vim:E5555: API call: Wrong type for argument 1, expecting Window'
[denite] Please execute :messages command.
```

- `:Denite buffer`

```

[denite] Traceback (most recent call last):
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/rplugin.py", line 26, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 144, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 196, in _start
[denite]     self._init_buffer()
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 221, in _init_buffer
[denite]     self._resize_buffer()
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 535, in _resize_buffer
[denite]     {'height': winheight})
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.nvim.NvimError: b'Vim:E5555: API call: Wrong type for argument 1, expecting Window'
[denite] Please execute :messages command.
```

## Environment Information (Required!)

 * denite version (SHA1):`67d21209b57d30f7f61a814dd2e236d39b29a216`

 * OS:macOS 10.14.5

 * Vim/neovim version:

```
NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190607-72538-1x5sb1j/build/config -I/tmp/neovim-20190607-72538-1x5sb1j/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190607-72538-1x5sb1j/build/src/nvim/auto -I/tmp/neovim-20190607-72538-1x5sb1j/build/include
Compiled by tracyone@t-mac.lan

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-8e8c7d7/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: xterm-256color
  - INFO: default-terminal: screen-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.4.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 3.5.2, latest: 4.5.0
    - ADVICE:
      - Run in shell: npm install -g neovim

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

````

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
scriptencoding utf-8
set nocompatible
let &rtp=&rtp.','.$HOME.'/.vim/bundle/denite.nvim'
set rtp+=$HOME.'/.vim/bundle/nvim-yarp'


autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>
                \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d
                \ denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> <c-t>
                \ denite#do_map('do_action', 'tabopen')
    nnoremap <silent><buffer><expr> <c-v>
                \ denite#do_map('do_action', 'vsplit')
    nnoremap <silent><buffer><expr> <c-x>
                \ denite#do_map('do_action', 'split')
    nnoremap <silent><buffer><expr> p
                \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q
                \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
                \ denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> V
                \ denite#do_map('toggle_select').'j'
endfunction


autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
    imap <silent><buffer> <tab> <Plug>(denite_filter_quit)
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    inoremap <silent><buffer><expr> <c-t>
                \ denite#do_map('do_action', 'tabopen')
    inoremap <silent><buffer><expr> <c-v>
                \ denite#do_map('do_action', 'vsplit')
    inoremap <silent><buffer><expr> <c-x>
                \ denite#do_map('do_action', 'split')
    inoremap <silent><buffer><expr> <esc>
                \ denite#do_map('quit')
    inoremap <silent><buffer> <C-j>
                \ <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
    inoremap <silent><buffer> <C-k>
                \ <Esc><C-w>p:call cursor(line('.')-1,0)<CR><C-w>pA
endfunction


" Change matchers.
call denite#custom#source(
\ 'file_mru', 'matchers', ['matcher/fuzzy', 'matcher/project_files'])

call denite#custom#source('tag', 'matchers', ['matcher/substring'])

call denite#custom#source('file/old', 'converters',
      \ ['converter/relative_word'])
" Change sorters.
call denite#custom#source(
\ 'file/rec', 'sorters', ['sorter/sublime'])


" Define alias
call denite#custom#alias('source', 'file/rec/git', 'file/rec')
call denite#custom#var('file/rec/git', 'command',
      \ ['git', 'ls-files', '-co', '--exclude-standard'])

call denite#custom#alias('source', 'file/rec/py', 'file/rec')
call denite#custom#var('file/rec/py', 'command',['scantree.py'])

" Change ignore_globs
call denite#custom#filter('matcher/ignore_globs', 'ignore_globs',
      \ [ '.git/', '.ropeproject/', '__pycache__/',
      \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

let s:denite_options = {
      \ 'prompt' : '>',
      \ 'split': 'floating',
      \ 'start_filter': 1,
      \ 'auto_resize': 1,
      \ 'source_names': 'short',
      \ 'direction': 'botright',
      \ 'highlight_filter_background': 'CursorLine',
      \ 'highlight_matched_char': 'Type',
      \ }

call denite#custom#option('default', s:denite_options)

colorscheme desert "default setting 
filetype plugin indent on
syntax on
```

## How to reproduce problems from neovim startup (Required!)

nvim -u minimal_vimrc

```vim
:Denite file
:Denite buffer
```

[log_py3_rplugin.log](https://github.com/Shougo/denite.nvim/files/3286980/log_py3_rplugin.log)

## Upload the log file

**Comment by kcoyner** [comment]
I'm experiencing the exact same issue.

**Comment by Shougo** [comment]
I will check it later.

**Comment by tracyone** [comment]
hi all, It seems that this issue can be solved if I remove option auto_resize.

**Comment by Shougo** [comment]
Please wait.  I will fix it.

**Comment by tracyone** [comment]
I am afraid of this commit only fix issue of command Denite buffer not Denite file

**Comment by Shougo** [comment]
I have fixed file kind instead.

**Comment by tracyone** [comment]
I just found not only Denite file but also Denite buffer, If you run them more then one time

```vim
:Denite file "work
:Denite file "not work
```

```

No matching autocommands
[denite] Traceback (most recent call last):
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/rplugin.py", line 26, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 144, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 196, in _start
[denite]     self._init_buffer()
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 224, in _init_buffer
[denite]     self._resize_buffer()
[denite]   File "/Users/tracyone/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 542, in _resize_buffer
[denite]     'col': int(self._context['wincol']),
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/Users/tracyone/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.nvim.NvimError: b'Vim:E5555: API call: Invalid window id'
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
@tracyone I don't reproduce the problem.
Do you use the latest version really?
Please create the reproduce instructions and reproduce minimal vimrc.

If not, I will ignore your issue.
It works for me.

**Comment by Shougo** [comment]
I have tested the vimrc.

```vim
set runtimepath+=~/work/denite.nvim/
let s:denite_options = {
      \ 'prompt' : '>',
      \ 'split': 'floating',
      \ 'start_filter': 1,
      \ 'auto_resize': 1,
      \ 'source_names': 'short',
      \ 'direction': 'botright',
      \ 'highlight_filter_background': 'CursorLine',
      \ 'highlight_matched_char': 'Type',
      \ }

call denite#custom#option('default', s:denite_options)

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>
                \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d
                \ denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> <c-t>
                \ denite#do_map('do_action', 'tabopen')
    nnoremap <silent><buffer><expr> <c-v>
                \ denite#do_map('do_action', 'vsplit')
    nnoremap <silent><buffer><expr> <c-x>
                \ denite#do_map('do_action', 'split')
    nnoremap <silent><buffer><expr> p
                \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q
                \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
                \ denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> V
                \ denite#do_map('toggle_select').'j'
endfunction

autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
    imap <silent><buffer> <tab> <Plug>(denite_filter_quit)
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    inoremap <silent><buffer><expr> <c-t>
                \ denite#do_map('do_action', 'tabopen')
    inoremap <silent><buffer><expr> <c-v>
                \ denite#do_map('do_action', 'vsplit')
    inoremap <silent><buffer><expr> <c-x>
                \ denite#do_map('do_action', 'split')
    inoremap <silent><buffer><expr> <esc>
                \ denite#do_map('quit')
    inoremap <silent><buffer> <C-j>
                \ <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
    inoremap <silent><buffer> <C-k>
                \ <Esc><C-w>p:call cursor(line('.')-1,0)<CR><C-w>pA
endfunction

colorscheme desert "default setting
filetype plugin indent on
syntax on
```

**Comment by Shougo** [comment]
And your vimrc is too long.  It is not minimal.

**Comment by Shougo** [comment]
Reproduced. And fixed.
