### ISSUE TITLE
rplugin.py crashes when encountering filenames containing newline characters

### ISSUE THREAD

**Issue by khughitt** [Shougo/denite.nvim#703]
# Problems summary

`rplugin.py` crashes when encountering filenames containing newline characters

## Expected

`rplugin.py` handles unfortunately-named files like these.

Ideally, no one should be creating files like these, but it happens, presumably by accident.

## Environment Information (Required!)

 * denite version (SHA1):

85fa3ed3b430df61d1b8aeb8772162acfebc1f46

 * OS:

Arch Linux Linux 5.2.5

 * Vim/neovim version:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#denite#check                                                                                                                                                                    
  3 ========================================================================                                                                                                               
  4 ## denite.nvim                                                                                                                                                                         
  5   - OK: has("python3") was successful                                                                                                                                                  
  6   - OK: Python3.6.1+ was successful                                                                                                                                                    
  7                                                                                                                                                                                        
  8 health#deoplete#check                                                                                                                                                                  
  9 ========================================================================                                                                                                                10 ## deoplete.nvim                                                                                                                                                                       
 11   - OK: exists("v:t_list") was successful                                                                                                                                              
 12   - OK: has("timers") was successful                                                                                                                                                   
 13   - OK: has("python3") was successful                                                                                                                                                  
 14   - OK: Require Python3.6.1+ was successful                                                                                                                                            
 15   - INFO: If you're still having problems, try the following commands:                                                                                                                 
 16     $ export NVIM_PYTHON_LOG_FILE=/tmp/log                                                                                                                                             
 17     $ export NVIM_PYTHON_LOG_LEVEL=DEBUG                                                                                                                                               
 18     $ nvim                                                                                                                                                                             
 19     $ cat /tmp/log_{PID}                                                                                                                                                               
 20     and then create an issue on github                                                                                                                                                 
 21                                                                                                                                                                                        
 22 health#nvim#check                                                                                                                                                                      
 23 ========================================================================                                                                                                               
 24 ## Configuration                                                                                                                                                                       
 25   - OK: no issues found                                                                                                                                                                
 26                                                                                                                                                                                        
 27 ## Performance                                                                                                                                                                         
 28   - OK: Build type: Release                                                                                                                                                            
 29                                                                                                                                                                                        
 30 ## Remote Plugins                                                                                                                                                                      
 31   - OK: Up to date                                                                                                                                                                     
 32                                                                                                                                                                                        
 33 ## terminal                                                                                                                                                                            
 34   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177                                                                                                                       
 35   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~                                                                                                                                  
 36   - INFO: $VTE_VERSION='5602'                                                                                                                                                          
 37   - INFO: $COLORTERM='truecolor'                                                                                                                                                       
 38                                                                                                                                                                                        
 39 health#provider#check                                                                                                                                                                  
 40 ========================================================================                                                                                                               
 41 ## Clipboard (optional)                                                                                                                                                                
 42   - OK: Clipboard tool found: xclip                                                                                                                                                    
 43                                                                                                                                                                                        
 44 ## Python 2 provider (optional)                                                                                                                                                        
 45   - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.                                                                 46   - ERROR: Python provider error:                                                                                                                                                      
 47     - ADVICE:                                                                                                                                                                          
 48       - provider/pythonx: Could not load Python 2:                                                                                                                                     
 49           /usr/bin/python2 does not have the "neovim" module. :help provider-python                                                                                                    
 50           /usr/bin/python2.7 does not have the "neovim" module. :help provider-python                                                                                                  
 51           python2.6 not found in search path or not executable.                                                                                                                        
 52           /home/keith/conda/bin/python is Python 3.7 and cannot provide Python 2.                                                                                                      
 53   - INFO: Executable: Not found                                                                                                                                                        
 54                                                                                                                                                                                        
 55 ## Python 3 provider (optional)                                                                                                                                                        
 56   - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.                                                                                                 
 57   - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.                                                                                           
 58   - INFO: Executable: /home/keith/conda/bin/python3                                                                                                                                    
 59   - INFO: Other python executable: /usr/bin/python3                                                                                                                                    
 60   - INFO: Python version: 3.7.3                                                                                                                                                        
 61   - INFO: pynvim version: 0.3.2                                                                                                                                                        
 62   - OK: Latest pynvim is installed.                                                                                                                                                    
 63                                                                                                                                                                                        
 64 ## Ruby provider (optional)                                                                                                                                                            
 65   - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]                                                                                                               
 66   - WARNING: `neovim-ruby-host` not found.                                                                                                                                             
 67     - ADVICE:                                                                                                                                                                          
 68       - Run `gem install neovim` to ensure the neovim RubyGem is installed.                                                                                                            
 69       - Run `gem environment` to ensure the gem bin directory is in $PATH.                                                                                                             
 70       - If you are using rvm/rbenv/chruby, try "rehashing".                                                                                                                            
 71       - See :help g:ruby_host_prog for non-standard gem installations.                                                                                                                 
 72                                                                                                                                                                                        
 73 ## Node.js provider (optional)                                                                                                                                                         
 74   - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.                                                                                                                            
 75     - ADVICE:                                                                                                                                                                          
 76       - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.                                    
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.config/nvim-tmp/plugged/denite.nvim/
```

## How to reproduce problems from neovim startup (Required!)

1. Create the problematic file:

```
mkdir /tmp/denite-bug
cd /tmp/denite-bug
touch $'foo\nbar'
nvim
```

2. Inside nvim, launch `file/rec`:

```
:Denite file/rec
```

## :messages

```
[denite] Traceback (most recent call last):                                                                                                                                                    
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 25, in start                                                                          
[denite]     return ui.start(args[0], context)                                                                                                                                                 
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start                                                                       
[denite]     self._start_sources_queue(context)                                                                                                                                                
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 151, in _start_sources_queue                                                       
[denite]     self._start(context['sources_queue'][0], context)                                                                                                                                 
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 196, in _start                                                                     
[denite]     self._gather_candidates()                                                                                                                                                         
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 729, in _gather_candidates                                                         
[denite]     self._denite.gather_candidates(self._context)                                                                                                                                     
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 32, in gather_candidates                                                               
[denite]     self._put('gather_candidates', [context])                                                                                                                                         
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 62, in _put                                                                            
[denite]     return self._child.main(name, args, queue_id=None)                                                                                                                                
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 67, in main                                                                             
[denite]     self.gather_candidates(args[0])                                                                                                                                                   
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 120, in gather_candidates                                                               
[denite]     source.context, source)                                                                                                                                                           
[denite]   File "/home/keith/.dotfiles/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 370, in _gather_source_candidates                                                       
[denite]     candidates = source.gather_candidates(context)                                                                                                                                    
[denite]   File "/home/keith/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/source/file/rec.py", line 87, in gather_candidates                                                        
[denite]     return self._async_gather_candidates(context, 0.5)                                                                                                                                
[denite]   File "/home/keith/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/source/file/rec.py", line 106, in _async_gather_candidates                                                
[denite]     } for x in outs if x != '']                                                                                                                                                       
[denite]   File "/home/keith/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/source/file/rec.py", line 106, in <listcomp>                                                              
[denite]     } for x in outs if x != '']                                                                                                                                                       
[denite]   File "/home/keith/conda/lib/python3.7/pathlib.py", line 876, in relative_to                                                                                                         
[denite]     .format(str(self), str(formatted)))                                                                                                                                               
[denite] ValueError: 'bar' does not start with '/tmp/denite-edge-case'                                                                                                                         
[denite] Please execute :messages command.    
```

## Screenshot

![2019-08-03-195349_938x1030_scrot](https://user-images.githubusercontent.com/125001/62417856-eea13480-b628-11e9-8ba4-c64ab8cef64c.png)

**Comment by khughitt** [comment]
Thanks for the quick fix!

I tested it out and denite no longer throws an error.

It does, however, show only a partial file name ("foo" instead of "foo\nbar"). The result of this is that attempting to open the file ends up opening a non-existent "foo" file.

Not a huge issue since I don't have any plans to actually look for such files, and can now safely ignore them, but I thought I would let you know.

Thanks for all your work on this great tool!!

**Comment by khughitt** [comment]
On a side note, any suggestions for resources to learn to debug nvim python plugins?

If there is a straight-forward way to set a breakpoint in `rec.py`, for example, I can take a stab at fixing this (and any other issues I come across in the future..)

I looked around some and read a bit about the pynvim API, but still unclear about the general workflow / debugging approach..

**Comment by Shougo** [comment]
> It does, however, show only a partial file name ("foo" instead of "foo\nbar"). The result of this is that attempting to open the file ends up opening a non-existent "foo" file.

Yes.  I know it and it is feature.  I cannot fix the problem because the process returns broken filenames.
If you can fix the problem, please create the PR.

**Comment by Shougo** [comment]
> I looked around some and read a bit about the pynvim API, but still unclear about the general workflow / debugging approach..

Unfortunately, no debugger for denite.
You can use print debug by `self.debug()`.

**Comment by khughitt** [comment]
Okay, I see the problem now. Ag splits the filenames across lines so they look like separate files. One could potentially work around this using something along the lines of:

```sh
ag --null --break --follow --nocolor --nogroup -g '' /tmp/denite-edge-case | tr '\012' ' ' | tr '\0' '\n'
```

But that is pretty messy and still only helps with displaying the missing filename part.

In any event, this is a pretty uncommon edge case, so probably not worth spending any more time on.

I appreciate the suggestion about `self.debug()` - that was helpful!

Cheers.
