### ISSUE TITLE
Cannot jump to preview window

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#775]
Consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

au FileType denite call s:denite_mappings()

function! s:denite_mappings() abort
    nnoremap <silent><buffer><expr> <A-v> denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> <A-j> denite#do_map('do_action', 'scroll_preview_down')
endfunction

function! s:scroll_preview_down(context)
    wincmd P
    execute 'normal! 10j'
    wincmd p
endfunction
call denite#custom#action('file', 'scroll_preview_down',
            \ function('s:scroll_preview_down'), {'is_quit': 0})
```
Now, as in the GIF, open nvim and do:
1. Run `:Denite file`
2. Press `<A-v>` on some candidate to trigger preview
3. Run `:wincmd P` to jump to the preview window and then `:wincmd P` to jump back to the denite buffer
4. Now press `<A-j>`

After 4, the following error message is shown:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/rplugin.py", line 65, in do_map
[denite]     return do_map(ui, args[1], args[2])
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/map.py", line 20, in do_map
[denite]     return MAPPINGS[name](denite, params)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/map.py", line 66, in _do_action
[denite]     return denite.do_action(name, is_manual=True)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 91, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/parent.py", line 63, in do_action
[denite]     return self._get('do_action', [context, action_name, targets])
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/parent.py", line 84, in _get
[denite]     return self._put(name, args)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=None)  # type: ignore
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/child.py", line 79, in main
[denite]     ret = self.do_action(args[0], args[1], args[2])
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/child.py", line 262, in do_action
[denite]     else self._vim.call(
[denite]   File "/home/pedro/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.common.NvimError: Vim(wincmd):E441: There is no preview window
[denite] Please execute :messages command.
```
I expect that by press `<A-j>` I can jump to the preview window (since `:wincmd P` does work)

![Peek 2020-04-16 12-12](https://user-images.githubusercontent.com/2583971/79473487-92761900-7fdb-11ea-8550-97468e6473a1.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thanks
