### ISSUE TITLE
-preview-width option causes error

### ISSUE THREAD

**Issue by machel2** [Shougo/denite.nvim#777]
# Problems summary
Python errors when -preview-width option is specified, preview window is displayed but has very narrow width (few columns)

```
[denite] Traceback (most recent call last):
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 65, in do_map
[denite]     return do_map(ui, args[1], args[2])
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/map.py", line 20, in do_map
[denite]     return MAPPINGS[name](denite, params)
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/map.py", line 66, in _do_action
[denite]     return denite.do_action(name, is_manual=True)
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 91, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 63, in do_action
[denite]     return self._get('do_action', [context, action_name, targets])
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 84, in _get
[denite]     return self._put(name, args)
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=None)  # type: ignore
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 79, in main
[denite]     ret = self.do_action(args[0], args[1], args[2])
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 260, in do_action
[denite]     new_context = (action['func'](context)
[denite]   File "/home/mh/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/kind/file.py", line 63, in action_preview
[denite]     self.vim.call('denite#helper#preview_file', context, path)
[denite]   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.common.NvimError: Vim(call):E5555: API call: 'width' key must be a positive Integer
[denite] Please execute :messages command.
```

## Expected
No errors. Preview window of specified width

## Environment Information (Required!)

 * denite version (SHA1): 3.3

 * OS: Linux

 * Vim/neovim version: Neovim 0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
```
```
## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call denite#custom#var('file/rec', 'command', ['find', '-L', ':directory',
  \ '-path', '*/.git/*', '-prune', '-o',
  \ '-path', '*/.phpcd/*', '-prune', '-o',
  \ '-type', 'l', '-print', '-o', '-type', 'f', '-print'])
nnoremap <C-p> :DeniteProjectDir -split=floating -wincol=4 -winrow=40 -vertical-preview -floating-preview -preview-height=40 -preview-width=100 file/rec<CR>
nnoremap <C-[> :DeniteProjectDir grep<CR>
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
  nnoremap <silent><buffer><expr> h denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
  nnoremap <silent><buffer> <C-t> :w t-search-files \| tabnew t-search-files<CR>
endfunction
```

## How to reproduce problems from neovim startup (Required!)

 1. open denite with 'C-p' key (defined in init.vim) or run: `Denite -split=floating -wincol=4 -winrow=40 -vertical-preview -floating-preview -preview-height=40 -preview-width=100 file/rec`
 2. open preview window with 'p' key
[log.txt](https://github.com/Shougo/denite.nvim/files/4499283/log.txt)

**Comment by Shougo** [comment]
Fixed.
