### ISSUE TITLE
No filtering with matchdelete and window id not found

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#782]
Consider the following minimal init.vim file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
    \ 'auto_resize': 1,
    \ 'statusline': 0,
    \ 'reversed': 1,
    \ 'match_highlight': 1,
    \ 'start_filter': 1,
    \ 'filter_updatetime': 100,
\ })
```
Now, as in the GIF, open latest neovim (with [this patch](https://github.com/neovim/neovim/pull/12325)), and do
1. Run `:Denite file`
2. Press some filtering characters -> candidates are not filtered until I exit insert mode.
3. Close the Denite and Denite filter buffers (with :q) and run `:Denite file` again -> I get the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 165, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 224, in _start
[denite]     self._update_buffer()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 534, in _update_buffer
[denite]     self._vim.call('matchdelete',
[denite]   File "/home/pedro/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.common.NvimError: Vim:E803: ID not found: 6
[denite] Please execute :messages command.
```

![Peek 2020-05-16 19-17](https://user-images.githubusercontent.com/2583971/82131289-f1c97380-97a9-11ea-9896-270c46fd8069.gif)

**Comment by Shougo** [comment]
> Press some filtering characters -> candidates are not filtered until I exit insert mode.

It is my porting bug.

https://github.com/neovim/neovim/pull/12328 fixes the problem.

**Comment by petobens** [comment]
Thanks
