### ISSUE TITLE
[Feature Request] Relative winwidth

### ISSUE THREAD

**Issue by juancampa** [Shougo/denite.nvim#800]
# Problems summary

I just discovered `-split=floating` which I think it's amazing, I'd like to make it wider but it seems like `-winwidth`/`-wincol`/etc... only take absolute values and not relative (i.e. a percentage of the screen)

## Expected

```
:Denite -split=floating -marginleft=5 -marginright=5
```
So it's 5 columns from the left and 5 columns from the right.

**Any way to achieve this?**

## Environment Information (Required!)

 * denite version (SHA1): `5fbc044e3e8ecf80c589d6e87859dcc4c005f2e5`

 * OS: Linux/Arch

 * Vim/neovim version: `v0.4.4`

**Comment by Shougo** [comment]
This seems good feature.  But to implement the feature is very hard.
Denite already implements `foating_relative` feature.

**Comment by Shougo** [comment]
```vim
:Denite -split=floating -winwidth=`winwidth(0)-5` -winheight=`winheight`(0)-5
```

**Comment by juancampa** [comment]
@Shougo how do you specify that in a noremap statement, if you don't mind me asking?

This doesn't seem to work:
```
nnoremap <C-p> :<C-u>Denite -start-filter -split=floating -wincol=10 -winwidth=`&columns-10` buffer file/rec file_mru<CR><CR>
```
I get this error
```
[denite] Please execute :messages command.
[denite] Traceback (most recent call last):
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 165, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 214, in _start
[denite]     self._update_candidates()
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 477, in _update_candidates
[denite]     self._candidates] = self._denite.filter_candidates(self._context)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/parent.py", line 59, in filter_candidates
[denite]     return self._get('filter_candidates', [context])
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/parent.py", line 84, in _get
[denite]     return self._put(name, args)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=None)  # type: ignore
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/child.py", line 77, in main
[denite]     ret = self.filter_candidates(args[0])
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/child.py", line 209, in filter_candidates
[denite]     for status, partial, patterns, entire_len in self._filter_candidates(
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/child.py", line 346, in _filter_candidates
[denite]     candidates = self._filter_source_candidates(ctx, source)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/child.py", line 386, in _filter_source_candidates
[denite]     ctx['candidates'] = f.filter(ctx)
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/filter/converter/truncate_abbr.py", line 23, in filter
[denite]     candidate['abbr'] = truncate(
[denite]   File "/home/juan/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/util.py", line 326, in truncate
[denite]     if (strwidth(vim, word) > max_length or
[denite] TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by Shougo** [comment]
It is the bug of denite.nvim.
Please update to the latest version.

**Comment by juancampa** [comment]
It works great now, thanks!
