### ISSUE TITLE
matcher/clap KeyError with deep nested file

### ISSUE THREAD

**Issue by rafi** [Shougo/denite.nvim#801]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Using file/rec with `matcher/clap` and a very deep nested file causes an error on Neovim.

```
Traceback (most recent call last):
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 65, in do_map
    return do_map(ui, args[1], args[2])
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/map.py", line 20, in do_map
    return MAPPINGS[name](denite, params)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/map.py", line 95, in _filter_async
    denite._update_candidates()
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 444, in _update_candidates
    self._candidates] = self._denite.filter_candidates(self._context)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 59, in filter_candidates
    return self._get('filter_candidates', [context])
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 84, in _get
    return self._put(name, args)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 80, in _put
    return self._child.main(name, args, queue_id=None)  # type: ignore
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 77, in main
    ret = self.filter_candidates(args[0])
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 209, in filter_candidates
    for status, partial, patterns, entire_len in self._filter_candidates(
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 346, in _filter_candidates
    candidates = self._filter_source_candidates(ctx, source)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 377, in _filter_source_candidates
    self._match_candidates(ctx, matchers)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 430, in _match_candidates
    context['candidates'] = self._call_matchers(ctx, matchers)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 435, in _call_matchers
    ctx['candidates'] = matcher.filter(ctx)
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/filter/matcher/clap.py", line 53, in filter
    return [d[x] for x in result[1]]
  File "/Users/rafi/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/filter/matcher/clap.py", line 53, in <listcomp>
    return [d[x] for x in result[1]]
KeyError: '../lib/rule-viewer/rule-drilldown-layout/rule-drill-down-related-tickets/related-tickets-cards-container/related-tickets-card/related-tickets-card-content/related-tickets-card-
content.component.scss'
```

## Expected
No error while entering input in filter window.

## Environment Information (Required!)

 * denite version (SHA1): b9b332a3

 * OS: macOS

 * Vim/neovim version: `NVIM v0.5.0-f34eeba2d`

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" minimal vimrc
if &compatible | set nocompatible | endif

let g:python3_host_prog = $XDG_DATA_HOME . '/python/pyenv/versions/neovim/bin/python'

let $DEIN_DIR = $XDG_CACHE_HOME . '/vim/dein/repos/github.com/'
set runtimepath^=$DEIN_DIR/Shougo/denite.nvim
set runtimepath^=$DEIN_DIR/liuchengxu/vim-clap

call denite#custom#option('_', {
	\ 'start_filter': v:true,
	\ 'smartcase': v:true,
	\ })

nnoremap <silent><LocalLeader>f :<C-u>Denite file/rec<CR>

call denite#custom#filter('matcher/clap', 'clap_path', $DEIN_DIR.'/liuchengxu/vim-clap')
call denite#custom#source('file/rec', 'matchers', [ 'matcher/clap' ])

filetype plugin indent on
syntax enable
```

## How to reproduce problems from neovim startup (Required!)

 1. `mkdir -p ui/projects/rule/src/lib/rule-viewer/rule-drilldown-layout/rule-drill-down-related-tickets/related-tickets-cards-container/related-tickets-card/related-tickets-card-content/`
 2. `touch ui/projects/rule/src/lib/rule-viewer/rule-drilldown-layout/rule-drill-down-related-tickets/related-tickets-cards-container/related-tickets-card/related-tickets-card-content/related-tickets-card-content.component.scss`
 3. Start nvim
 4. `:Denite file/rec`
 5. In input window, type: `related sc`
 6. In command-mode, run `:message`

Errors are shown. (Pasted aboved)

**Comment by Shougo** [comment]
I have added key check.

**Comment by rafi** [comment]
@Shougo Thanks. Error is gone, but now I can't find the file if I type `related sc`
If I run `:Clap files` and input `related sc` -- vim-clap finds the file. Same reproducible scenario & minimal vimrc.

**Comment by Shougo** [comment]
Your candidate width is too long.

You can change the option.

```
					*denite-option-max-candidate-width*
-max-candidate-width={width}
		Specify the max candidate width.
		Note: Denite skip the match after the width.
		Default: 200
```
