### ISSUE TITLE
:Denite buffer fails with 'KeyError'

### ISSUE THREAD

**Issue by echacko** [Shougo/denite.nvim#809]
# Problems summary
:Denite buffer commands fails with key error. :Denite file/rec is working without any issues. 

```
[denite] Traceback (most recent call last):                                                                                                                      
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 165, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 212, in _start
[denite]     self._init_denite()
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 833, in _init_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 50, in on_init
[denite]     self._put('on_init', [context])
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=None)  # type: ignore
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 71, in main
[denite]     self.on_init(args[0])
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 161, in on_init
[denite]     source.on_init(source.context)
[denite]   File "/home/echacko/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/source/buffer.py", line 43, in on_init
[denite]     self.vars['only_modified'])
[denite] KeyError: 'only_modified'
[denite] Please execute :messages command.
Press ENTER or type command to continue
```

## Expected
:Denite buffer should not result in an error.

## Environment Information (Required!)

 * denite version (SHA1): [842de8c](https://github.com/Shougo/denite.nvim/commit/842de8c1a5126ab7af082d8462ff19c6a9930499)

 * OS: Arch Linux 5.9.1-arch1-1 86_64 GNU/Linux

 * Vim/neovim version:
```
NVIM v0.5.0-767-g0f590ae2a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-25142a98-669f-4031-af45-e52ceeff1b4f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5602'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.6
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.14.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.local/share/nvim/plugged/denite.nvim

```

## How to reproduce problems from neovim startup (Required!)

 1. Run ```:Denite buffer```

## Upload the log file

[nvim.log](https://github.com/Shougo/denite.nvim/files/5421445/nvim.log)

**Comment by Shougo** [comment]
Fixed
