### ISSUE TITLE
all :Denite commands occurs python error

### ISSUE THREAD

**Issue by IrisRainbow7** [Shougo/denite.nvim#812]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
all `:Denite` commands occurs python error

ex. `:Denite buffer `
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/*****/.vim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/Users/*****/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/Users/*****/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 165, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/*****/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 214, in _start
[denite]     self._update_candidates()
[denite]   File "/Users/*****/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 443, in _update_candidates
[denite]     [self._is_async, pattern, statuses, self._entire_len,
[denite] ValueError: too many values to unpack (expected 5)
[denite] Please execute :messages command.
``` 

## Expected
no errors, run Denite

## Environment Information (Required!)

 * denite version (SHA1): 31c35b5

 * OS: macOS Big Sur 11.1

 * Vim/neovim version:
 ```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20201114-45415-1dcr9av/neovim-0.4.4/build/config -I/tmp/neovim-20201114-45415-1dcr9av/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20201114-45415-1dcr9av/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201114-45415-1dcr9av/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20201114-45415-1dcr9av/neovim-0.4.4/build/include
Compiled by brew@BigSur
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 ```

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 1ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
let g:python3_host_prog = '/usr/bin/python3'
call plug#begin('~/.vim/plugged')
Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
```

## How to reproduce problems from neovim startup (Required!)

 1. `:Denite buffer`, `:Denite file/rec`, `:Denite grep` then input any patterns, and `:Denite line` commands all occurs same error above.

## Generate a logfile if appropriate

trying, but no logs.

**Comment by Shougo** [comment]
Please use git bisect for it.

**Comment by arghasen** [comment]
Facing same issue, I am running it in an empty folder. So not sure how can git bisect

**Comment by arghasen** [comment]
I am facing same issue, am i bisecting the right place? 
~/.cache/dein/repos/github.com/Shougo/denite.nvim

**Comment by Shougo** [comment]
Really?
Denite had worked before?

I don't reproduce the error.

**Comment by belka-ew** [comment]
I can confirm the issue on Linux and WSL2. Commit `cbfac90` works, `31c35b5` triggers the error.

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -fPIC -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/SBo/neovim-0.4.4/build/config -I/tmp/SBo/neovim-0.4.4/src -I/usr/include -I/tmp/SBo/neovim-0.4.4/build/src/nvim/auto -I/tmp/SBo/neovim-0.4.4/build/include
Compiled by root@darkstar.example.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```
health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
```

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
I have reverted the commit.
