### ISSUE TITLE
util.pyのfind_rpluginsでエラー

### ISSUE THREAD

**Issue by octaltree** [Shougo/denite.nvim#815]
# Problems summary
dein上で最新 f7667ec03c4 を使用したときに次のエラーを吐いた。
最小の`set runtimepath+=denite`だとエラーを吐かなかったので
deinを併用した最小のinit.vimを用意した。
a00d42aa1 の前後でエラーを吐くようになった。
```
[denite] Traceback (most recent call last):
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/ui/default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/ui/default.py", line 165, in _start_so
urces_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/ui/default.py", line 212, in _start
[denite]     self._init_denite()
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/ui/default.py", line 834, in _init_den
ite
[denite]     self._denite.start(self._context)
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/parent.py", line 44, in start
[denite]     self._put('start', [context])
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=0)
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/child.py", line 66, in main
[denite]     self.start(args[0])
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/child.py", line 92, in start
[denite]     self._load_sources(context)
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/child.py", line 450, in _load_sources
[denite]     for SourceClass, path, _ in rplugins:
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/util.py", line 255, in import_rplugins
[denite]     for path, module_path in find_rplugins(context, source, loaded_paths):
[denite]   File "/home/octaltree/.config/nvim/dein/.cache/with_dein.vim/.dein/rplugin/python3/denite/util.py", line 230, in find_rplugins
[denite]     module_path = str(Path(path).relative_to(root))[: -3]
[denite]   File "/usr/lib/python3.9/pathlib.py", line 928, in relative_to
[denite]     raise ValueError("{!r} is not in the subpath of {!r}"
[denite] ValueError: '/home/octaltree/.dotfiles/home/.config/nvim/dein/repos/github.com/Shougo/dein.vim/rplugin/python3/denite/source/dein.
py' is not in the subpath of '/home/octaltree/.config/nvim/dein/repos/github.com/Shougo/dein.vim/rplugin/python3/denite/source' OR one path
 is relative and the other is absolute.
[denite] Please execute :messages command.
```
## Environment Information (Required!)

 * denite version (SHA1): f7667ec03c4

 * OS: Linux version 5.10.2-2-MANJARO (builduser@LEGION) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020

 * Vim/neovim version:
 ```
NVIM v0.5.0-846-g569e5c86b
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/octaltree/.cache/yay/neovim-git/src/build/config -I/home/octaltree/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/octaltree/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/octaltree/.cache/yay/neovim-git/src/build/include
Compiled by octaltree@coorie

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 ```
health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 1
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.1
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
  - INFO: Host: /usr/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v15.4.0
  - INFO: Nvim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
 ```

## Provide a minimal init.vim with less than 50 lines (Required!)
```vim
if &compatible
  set nocompatible
endif

let g:dein_dir = "/home/octaltree/.config/nvim/dein"
let s:dein_repo_dir = g:dein_dir . "/repos/github.com/Shougo/dein.vim"

if filereadable(s:dein_repo_dir . "/bin/installer.sh")
  execute 'set runtimepath^=' . s:dein_repo_dir

  if dein#load_state(g:dein_dir)
    call dein#begin(g:dein_dir)
    call dein#add('Shougo/denite.nvim')
    call dein#end()
    call dein#save_state()
  endif

  if dein#check_install()
    call dein#install()
  endif
endif

filetype plugin indent on
syntax enable

nnoremap [Denite] <Nop>
nmap <silent><space> [Denite]
nnoremap [Denite]<space> :Denite source<CR>
```

## How to reproduce problems from neovim startup (Required!)
git checkoutしてvimの再起動をしながら
:call dein#update()
:UpdateRemotePlugins
:Denite source
でエラーを吐くversionを探したら a00d42aa1 だった。
~/.config/nvim/dein/{cache_nvim,state_nvim.vim,.cache}と
~/.local/share/nvim/rplugin.vimを消しても再現したので
キャッシュ事故は起こしていないと思われる。

**Comment by Shougo** [comment]
Fixed.
