### ISSUE TITLE
[denite] OSError: [WinError 123] when a terminal buffer exists on Windows

### ISSUE THREAD

**Issue by igrep** [Shougo/denite.nvim#817]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

`:Denite buffer` doesn't work due to `[denite] OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。`  when a terminal buffer exists on Windows.

## Expected

`:Denite buffer` should open a denite buffer to choose a buffer.

## Environment Information (Required!)

 * denite version (SHA1): f4a47a829ede8d1e49c57fe25ea76c9d083e6067

 * OS: Windows 10 20H2

 * Vim/neovim version: `NVIM v0.5.0-753-g4b00916e9`

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "denite.nvim" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - ERROR: command failed: infocmp -L
    infocmp: couldn't open terminfo file /usr/share/terminfo/76/vtpcon.

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Python37\python.EXE is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Python37\python.EXE
  - INFO: Other python executable: C:/Python37/python
  - INFO: Python version: 3.7.3^M
  - INFO: pynvim version: 0.3.2^M (outdated; from C:\Python37\lib\site-packages\neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.2

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v15.5.0^M
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - ERROR: Require msgpack 1.0.0+ was not successful
    - ADVICE:
      - Please install/upgrade msgpack 1.0.0+.
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/denite.nvim/
```

## How to reproduce problems from neovim startup (Required!)

 1. nvim -u minimum-init.vim
 2. `:term`
 3. `Denite buffer`

## The result of `:messages` after the error

```
[denite] Traceback (most recent call last):
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\ui\default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\ui\default.py", line 165, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\ui\default.py", line 213, in _start
[denite]     self._gather_candidates()
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\ui\default.py", line 843, in _gather_candidates
[denite]     self._denite.gather_candidates(self._context)
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\parent.py", line 47, in gather_candidates
[denite]     self._put('gather_candidates', [context])
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=0)
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\child.py", line 68, in main
[denite]     self.gather_candidates(args[0])
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\child.py", line 121, in gather_candidates
[denite]     source.context, source)
[denite]   File "C:/Users/yuji-yamamoto/.cache/dein/.cache/init.vim/.dein/rplugin/python3\denite\child.py", line 392, in _gather_source_candidates
[denite]     candidates = source.gather_candidates(context)
[denite]   File "C:\Users\yuji-yamamoto\.cache\dein\repos\github.com\Shougo\denite.nvim\rplugin\python3\denite\source\buffer.py", line 63, in gather_candidates
[denite]     for x in self.vim.buffers]:
[denite]   File "C:\Users\yuji-yamamoto\.cache\dein\repos\github.com\Shougo\denite.nvim\rplugin\python3\denite\source\buffer.py", line 63, in <listcomp>
[denite]     for x in self.vim.buffers]:
[denite]   File "C:\Users\yuji-yamamoto\.cache\dein\repos\github.com\Shougo\denite.nvim\rplugin\python3\denite\source\buffer.py", line 121, in _get_attributes
[denite]     if Path(attr['name']).exists() else time())
[denite]   File "C:\Python37\lib\pathlib.py", line 1339, in exists
[denite]     self.stat()
[denite]   File "C:\Python37\lib\pathlib.py", line 1161, in stat
[denite]     return self._accessor.stat(self)
[denite] OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: 'term:\\D:\\d\\nvim-related-bug\\19752:C:\\WINDOWS\\system32\\cmd.exe'
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
Fixed.
