### ISSUE TITLE
vim-clapを用いたfile/rec検索をするとエラー

### ISSUE THREAD

**Issue by kbwo** [Shougo/denite.nvim#824]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
vim-clapの最新  https://github.com/liuchengxu/vim-clap/commit/d3536cae87fc9ac106f25f0a2d8d96c697bccb08  で下記のエラーを吐いた。
一つ前のコミット https://github.com/liuchengxu/vim-clap/commit/890aaca21af5ce9569d4393f72240283c198a246 ではエラーは起きず、通常通りの使用ができた。

```
[denite] Traceback (most recent call last):
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 68, in do_map
[denite]     ret = do_map(ui, args[1], args[2])
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/map.py", line 21, in do_map
[denite]     return MAPPINGS[name](denite, params)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/map.py", line 89, in _filter
[denite]     denite._update_candidates()
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 455, in _update_candidates
[denite]     self._candidates] = self._denite.filter_candidates(self._context)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 60, in filter_candidates
[denite]     return self._get('filter_candidates', [context])
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 85, in _get
[denite]     return self._put(name, args)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/parent.py", line 81, in _put
[denite]     return self._child.main(name, args, queue_id=0)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 77, in main
[denite]     ret = self.filter_candidates(args[0])
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 209, in filter_candidates
[denite]     for status, partial, patterns, entire_len in self._filter_candidates(
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 347, in _filter_candidates
[denite]     candidates = self._filter_source_candidates(ctx, source)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 378, in _filter_source_candidates
[denite]     self._match_candidates(ctx, matchers)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 431, in _match_candidates
[denite]     context['candidates'] = self._call_matchers(ctx, matchers)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/child.py", line 436, in _call_matchers
[denite]     ctx['candidates'] = matcher.filter(ctx)
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/filter/matcher/clap.py", line 50, in filte
[denite]     result = self._get_clap_result(
[denite]   File "/home/kodai/.vim/plugged/denite.nvim/rplugin/python3/denite/filter/matcher/clap.py", line 62, in _get_clap_result
[denite]     candidates = fuzzymatch_rs.fuzzy_match(
[denite] TypeError: fuzzy_match() missing required positional argument: recent_files
[denite] Please execute :messages command.
```

## Environment Information (Required!)

 * denite version (SHA1): 8774f3b9921a5d5807cb8f3742bb43c86839e423

 * OS:OS: Arch Linux x86_64

 * Vim/neovim version: neovim v0.4.4 / v0.5.0

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 ```

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /usr/share/pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/kodai/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /home/kodai/.pyenv/shims/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim

if has('vim_starting')
  set nocompatible
endif

call plug#begin(expand('~/.vim/plugged'))
Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
call plug#end()

call denite#custom#var('file/rec', 'command',
      \ ['rg', '--files', '--hidden', '--glob', '!.git', '--color', 'never'])
call denite#custom#filter('matcher/clap',
      \ 'clap_path', expand('~/.vim/plugged/vim-clap'))
call denite#custom#source('file/rec', 'matchers', [
      \ 'matcher/clap',
      \ ])

```

## How to reproduce problems from neovim startup (Required!)

deniteとvim-clapのインストール、clapのバイナリインストールをし、marcher/clapを設定するとエラーが起きる。denite/vim-clapそれぞれアンインストールとキャッシュ削除を試し、上記のようにclapのバージョンのみ変えたところ、 vim-clapの https://github.com/liuchengxu/vim-clap/commit/d3536cae87fc9ac106f25f0a2d8d96c697bccb08 でのみエラーが起きることを確認。

**Comment by Shougo** [comment]
修正しました
